R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
	//class SAFChoppers
 			"rhssaf_airforce_ht48",
	//class GREFChoppers
				"rhsgref_mi24g_CAS",
				"rhsgref_mi24g_FAB",
				"rhsgref_mi24g_UPK23",
	"MV22",
	//class RHSChoppers
			"RHS_AH1Z",
			"RHS_AH1Z_CS",
			"RHS_AH1Z_GS",
			"RHS_AH1Z_wd",
			"RHS_AH1Z_wd_CS",
			"RHS_AH1Z_wd_GS",
			"RHS_AH64D",
			"RHS_AH64DGrey",
			"RHS_AH64D_AA",
			"RHS_AH64D_CS",
			"RHS_AH64D_GS",
			"RHS_AH64D_wd",
			"RHS_AH64D_wd_AA",
			"RHS_AH64D_wd_CS",
			"RHS_AH64D_wd_GS",
			"RHS_CH_47F",
			"RHS_CH_47F_10",
			"RHS_CH_47F_light",
			"RHS_Ka52_UPK23_vvs",
			"RHS_Ka52_UPK23_vvsc",
			"RHS_Ka52_vvs",
			"RHS_Ka52_vvsc",
			"RHS_MELB_AH6M",
			"RHS_MELB_AH6M_H",
			"RHS_MELB_AH6M_M",
			"RHS_MELB_H6M",
			"RHS_MELB_MH6M",
			"RHS_MI8MTV3_UPK23_vvs",
			"RHS_MI8MTV3_UPK23_vvsc",
			"RHS_MI8MTV3_vvs",
			"RHS_MI8MTV3_vvsc",
			"RHS_Mi8MTV3_heavy_vdv",
			"RHS_Mi8MTV3_heavy_vvs",
			"RHS_Mi8MTV3_heavy_vvsc",
			"RHS_Mi8mtv3_Cargo_vdv",
			"RHS_Mi8mtv3_Cargo_vvs",
			"RHS_Mi8mtv3_Cargo_vvsc",
			"RHS_Mi24P_AT_vdv",
			"RHS_Mi24P_AT_vvs",
			"RHS_Mi24P_AT_vvsc",
			"RHS_Mi24P_CAS_vdv",
			"RHS_Mi24P_CAS_vvs",
			"RHS_Mi24P_CAS_vvsc",
			"RHS_Mi24P_vdv",
			"RHS_Mi24P_vvs",
			"RHS_Mi24P_vvsc",
			"RHS_Mi24V_AT_vvs",
			"RHS_Mi24V_AT_vvsc",
			"RHS_Mi24V_FAB_vdv",
			"RHS_Mi24V_FAB_vvs",
			"RHS_Mi24V_FAB_vvsc",
			"RHS_Mi24V_UPK23_vdv",
			"RHS_Mi24V_UPK23_vvs",
			"RHS_Mi24V_UPK23_vvsc",
			"RHS_Mi24V_vdv",
			"RHS_Mi24V_vvs",
			"RHS_Mi24V_vvsc",
			"RHS_Mi24Vt_vvs",
			"RHS_Mi24Vt_vvsc",
			"RHS_Mi8AMTSh_FAB_vvs",
			"RHS_Mi8AMTSh_FAB_vvsc",
			"RHS_Mi8AMTSh_UPK23_vvs",
			"RHS_Mi8AMTSh_UPK23_vvsc",
			"RHS_Mi8AMTSh_vvs",
			"RHS_Mi8AMTSh_vvsc",
			"RHS_Mi8AMT_vdv",
			"RHS_Mi8AMT_vvs",
			"RHS_Mi8AMT_vvsc",
			"RHS_Mi8MTV3_FAB_vdv",
			"RHS_Mi8MTV3_FAB_vvs",
			"RHS_Mi8MTV3_FAB_vvsc",
			"RHS_Mi8MTV3_UPK23_vdv",
			"RHS_Mi8MTV3_vdv",
			"RHS_Mi8amt_civilian",
			"RHS_Mi8mt_Cargo_vdv",
			"RHS_Mi8mt_Cargo_vv",
			"RHS_Mi8mt_Cargo_vvsc",
			"RHS_Mi8mt_vdv",
			"RHS_Mi8mt_vv",
			"RHS_Mi8mt_vvs",
			"RHS_Mi8mt_vvsc",
			"RHS_UH1Y",
			"RHS_UH1Y_FFAR",
			"RHS_UH1Y_FFAR_d",
			"RHS_UH1Y_UNARMED_d",
			"RHS_UH1Y_d",
			"RHS_UH60M",
			"RHS_UH60M_MEV",
			"RHS_UH60M_MEV2",
			"RHS_UH60M_MEV_d",
			"RHS_UH60M_d",
			"rhs_Mi8mt_cargo_vvs",
			"rhs_UH1Y_unarmed",
			"rhs_UH60M_MEV2_d",
			"RHS_UH60M2",
			"RHS_UH60M2_d",
			"RHS_UH60M_ESSS",
			"RHS_UH60M_ESSS2",
			"RHS_UH60M_ESSS_d",
			"RHS_UH60M_ESSS2_d",
			"rhs_ka60_c",
			"rhs_ka60_grey",
			"rhs_mi28n_s13_vvs",
			"rhs_mi28n_s13_vvsc",
			"rhs_mi28n_vvs",
			"rhs_mi28n_vvsc",
			"rhsusf_CH53E_USMC",
			"rhsusf_CH53E_USMC_D",
	//class CUPChoppers
			"CUP_B_AH1Z_NoWeapons",
			"CUP_B_AH6J_ESCORT_USA",
			"CUP_B_AW159_Unarmed_BAF",
			"CUP_B_CH47F_GB",
			"CUP_B_CH47F_USA",
			"CUP_B_CH53E_GER",
			"CUP_B_CH53E_USMC",
			"CUP_B_CH53E_VIV_GER",
			"CUP_B_MH60S_FFV_USMC",
			"CUP_B_MH60S_USMC",
			"CUP_B_MH6J_USA",
			"CUP_B_MI6A_CDF",
			"CUP_B_Mi171Sh_Unarmed_ACR",
			"CUP_B_Mi17_CDF",
			"CUP_B_Mi17_medevac_CDF",
			"CUP_B_UH1Y_MEV_F",
			"CUP_B_UH1Y_UNA_F",
			"CUP_B_UH60L_FFV_US",
			"CUP_B_UH60L_US",
			"CUP_B_UH60L_Unarmed_FFV_MEV_US",
			"CUP_B_UH60L_Unarmed_FFV_US",
			"CUP_B_UH60L_Unarmed_US",
			"CUP_B_UH60M_FFV_US",
			"CUP_B_UH60M_US",
			"CUP_B_UH60M_Unarmed_FFV_MEV_US",
			"CUP_B_UH60M_Unarmed_FFV_US",
			"CUP_B_UH60M_Unarmed_US",
			"CUP_C_Mi17_Civilian_RU",
			"CUP_I_UH60L_FFV_RACS",
			"CUP_I_UH60L_RACS",
			"CUP_I_UH60L_Unarmed_FFV_MEV_Racs",
			"CUP_I_UH60L_Unarmed_FFV_Racs",
			"CUP_I_UH60L_Unarmed_RACS",
			"CUP_O_Mi17_TK",
			"CUP_O_Mi8_medevac_CHDKZ",
			"CUP_O_Mi8_medevac_RU",
			
		"B_Heli_Transport_03_black_F",
		"B_Heli_Transport_03_F",
		"Exile_Chopper_Huron_Black",
		"Exile_Chopper_Huron_Green",
		"B_Heli_Transport_03_unarmed_F",		
		"B_Heli_Transport_03_unarmed_green_F",
		"Exile_Chopper_Mohawk_FIA",
		"C_IDAP_Heli_Transport_02_F",
		"I_Heli_Transport_02_F",
		//BW Heli
		"BW_AW159_Trans_Heer_F",
		"BW_AW159_Med_Heer_F",
		//"BW_AW159_CAS_Heer_F",
		"BW_AW101_Trans_Heer_F",
		"BW_AW101_Med_Heer_F",
		"BW_CH67_Trans_Heer_F",
		"BW_CH67_Med_Heer_F",
		"BW_Taru_SC_Heer_F"
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[

	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	
];