R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	//class SAFArmed
			"rhssaf_army_t72s",
			"rhssaf_m1025_olive_m2",

	//class SAFUnarmed
			"rhssaf_un_ural",
			"rhssaf_un_uaz",
			"rhssaf_un_uaz_open",
			"rhssaf_army_ural",
			"rhssaf_army_ural_open",
			"rhssaf_army_ural_fuel",
			"rhssaf_army_pts",
			"rhssaf_m998_olive_2dr_halftop",
			"rhssaf_m998_olive_2dr_fulltop",
			"rhssaf_m1025_olive",
		//class GREFArmed
			"rhsgref_BRDM2",
			"rhsgref_BRDM2UM",
			"rhsgref_BRDM2UM_b",
			"rhsgref_BRDM2UM_ins",
			"rhsgref_BRDM2UM_ins_g",
			"rhsgref_BRDM2UM_msv",
			"rhsgref_BRDM2UM_vdv",
			"rhsgref_BRDM2UM_vmf",
			"rhsgref_BRDM2_ATGM",
			"rhsgref_BRDM2_ATGM_b",
			"rhsgref_BRDM2_ATGM_ins",
			"rhsgref_BRDM2_ATGM_ins_g",
			"rhsgref_BRDM2_ATGM_msv",
			"rhsgref_BRDM2_ATGM_vdv",
			"rhsgref_BRDM2_ATGM_vmf",
			"rhsgref_BRDM2_HQ",
			"rhsgref_BRDM2_HQ_b",
			"rhsgref_BRDM2_HQ_ins",
			"rhsgref_BRDM2_HQ_ins_g",
			"rhsgref_BRDM2_HQ_msv",
			"rhsgref_BRDM2_HQ_vdv",
			"rhsgref_BRDM2_HQ_vmf",
			"rhsgref_BRDM2_b",
			"rhsgref_BRDM2_ins",
			"rhsgref_BRDM2_ins_g",
			"rhsgref_BRDM2_msv",
			"rhsgref_BRDM2_vdv",
			"rhsgref_BRDM2_vmf",
 			"rhsgref_un_m1117",
	//class GREFUnarmed
 			"rhsgref_cdf_reg_uaz_ags",
 			"rhsgref_cdf_reg_uaz_dshkm",
 			"rhsgref_cdf_reg_uaz_spg9",
	//class HVPCars
	"Mrshounka_corbillard_c",
	"Mrshounka_corbillard_c_bleufonce",
	"Mrshounka_corbillard_c_grise",
	"Mrshounka_corbillard_c_jaune",
	"Mrshounka_corbillard_c_noir",
	"Mrshounka_corbillard_c_orange",
	"Mrshounka_corbillard_c_rose",
	"Mrshounka_corbillard_c_rouge",
	"Mrshounka_corbillard_c_violet",
	"shounka_a3_dafxf_euro6_f",
	"shounka_f430_spider_bleufonce",
	"shounka_f430_spider_grise",
	"shounka_f430_spider_jaune",
	"shounka_f430_spider_noir",
	"shounka_f430_spider_orange",
	"shounka_f430_spider_rose",
	"shounka_f430_spider_rouge",
	"shounka_f430_spider_violet",
	"shounka_ivceco_bleufonce",
	"shounka_ivceco_grise",
	"shounka_ivceco_jaune",
	"shounka_ivceco_noir",
	"shounka_ivceco_orange",
	"shounka_ivceco_rose",
	"shounka_ivceco_rouge",
	"shounka_ivceco_violet",
	"shounka_limo_civ_bleufonce",
	"shounka_limo_civ_grise",
	"shounka_limo_civ_jaune",
	"shounka_limo_civ_noir",
	"shounka_limo_civ_orange",
	"shounka_limo_civ_rose",
	"shounka_limo_civ_violet",
	"Mrshounka_lykan_c_bleufonce",
	"Mrshounka_lykan_c_grise",
	"Mrshounka_lykan_c_jaune",
	"Mrshounka_lykan_c_noir",
	"Mrshounka_lykan_c_orange",
	"Mrshounka_lykan_c_rose",
	"Mrshounka_lykan_c_rouge",
	"Mrshounka_lykan_c_violet",
	"Mrshounka_a3_308_civ_bleufonce",
	"Mrshounka_a3_308_civ_grise",
	"Mrshounka_a3_308_civ_jaune",
	"Mrshounka_a3_308_civ_noir",
	"Mrshounka_a3_308_civ_orange",
	"Mrshounka_a3_308_civ_rose",
	"Mrshounka_a3_308_civ_rouge",
	"Mrshounka_a3_308_civ_violet",
	"SIG_Roadrunner",
	"SIG_Hubcaps",
	"SIG_Magnums",
	"SIG_Hcode",
	"SIG_Superbee",
	"SIG_SuperbeeY",
	"SIG_SuperbeeB",
	"SIG_SuperbeeL",
	"SIG_SuperbeeM",
	"SIG_SuperbeeG",
	"Mr_Own_buggy_bleufonce",
	"Mr_Own_buggy_grise",
	"Mr_Own_buggy_jaune",
	"Mr_Own_buggy_noir",
	"Mr_Own_buggy_orange",
	"Mr_Own_buggy_rose",
	"Mr_Own_buggy_rouge",
	"Mr_Own_buggy_violet",
	"Mr_Own_dodge15_civ",
	"Mr_Own_dodge15_civ_bleufonce",
	"Mr_Own_dodge15_civ_grise",
	"Mr_Own_dodge15_civ_jaune",
	"Mr_Own_dodge15_civ_noir",
	"Mr_Own_dodge15_civ_orange",
	"Mr_Own_dodge15_civ_rose",
	"Mr_Own_dodge15_civ_rouge",
	"Mr_Own_dodge15_civ_violet",
	"Mr_Own_hummer_civ_noir",
	"Mr_Own_hummer_civ_bleufonce",
	"Mr_Own_hummer_civ_grise",
	"Mr_Own_hummer_civ_jaune",
	"Mr_Own_hummer_civ_orange",
	"Mr_Own_hummer_civ_rose",
	"Mr_Own_hummer_civ_violet",
	"Mr_Own_hummer_civ_rouge",
	"shounka_buggy_bleufonce",
	"shounka_buggy_grise",
	"shounka_buggy_jaune",
	"shounka_buggy_noir",
	"shounka_buggy_orange",
	"shounka_buggy_rose",
	"shounka_buggy_rouge",
	"shounka_buggy_violet",
	"shounka_avalanche_bleufonce",
	"shounka_avalanche_grise",
	"shounka_avalanche_jaune",
	"shounka_avalanche_noir",
	"shounka_avalanche_orange",
	"shounka_avalanche_rose",
	"shounka_avalanche_rouge",
	"shounka_avalanche_violet",
	"shounka_monsteur_bleufonce",
	"shounka_monsteur_grise",
	"shounka_monsteur_jaune",
	"shounka_monsteur_noir",
	"shounka_monsteur_orange",
	"shounka_monsteur_rose",
	"shounka_monsteur_rouge",
	"shounka_monsteur_violet",
	"Mrshounka_Vandura_civ",
	"Mrshounka_Vandura_civ_bleufonce",
	"Mrshounka_Vandura_civ_grise",
	"Mrshounka_Vandura_civ_jaune",
	"Mrshounka_Vandura_civ_noir",
	"Mrshounka_Vandura_civ_orange",
	"Mrshounka_Vandura_civ_rose",
	"Mrshounka_Vandura_civ_rouge",
	"Mrshounka_Vandura_civ_violet",
	"Mrshounka_yamaha_p_bf",
	"Mrshounka_yamaha_p_g",
	"Mrshounka_yamaha_p_j",
	"Mrshounka_yamaha_p_noir",
	"Mrshounka_yamaha_p_o",
	"Mrshounka_yamaha_p_rose",
	"Mrshounka_yamaha_p_r",
	"Mrshounka_yamaha_p_v",
	//class FMPCars
			"FMP_Hunter_Alpha",
			"FMP_Hunter_Bgcamo",
			"FMP_Hunter_Grunge",
			"FMP_Hunter_Milsim",
			"FMP_Hunter_Ocamo",
			"FMP_Hunter_Savage",
			"FMP_Hunter_Skull",
			"FMP_Hunter_Suba",
			"FMP_Strider_Carbon",
			"FMP_Strider_Hex",
			"FMP_Strider_Multi",
			"FMP_Strider_Radioactive",
			"FMP_Strider_Rusty",
			"FMP_Strider_Splatter",
			"FMP_Strider_Standard",
			"bv_458_aqua",
			"bv_458_baby_blue",
			"bv_458_baby_pink",
			"bv_458_black2",
			"bv_458_burgundy",
			"bv_458_cardinal",
			"bv_458_dark_green",
			"bv_458_gold",
			"bv_458_green",
			"bv_458_grey",
			"bv_458_lavender",
			"bv_458_light_blue",
			"bv_458_light_yellow",
			"bv_458_lime",
			"bv_458_marina_blue",
			"bv_458_navy_blue",
			"bv_458_orange",
			"bv_458_pink",
			"bv_458_purple",
			"bv_458_red",
			"bv_458_sand",
			"bv_458_silver",
			"bv_458_skin_blue",
			"bv_458_skin_camo",
			"bv_458_skin_camo_urban",
			"bv_ben_dover_aqua",
			"bv_ben_dover_baby_blue",
			"bv_ben_dover_baby_pink",
			"bv_ben_dover_black2",
			"bv_ben_dover_burgundy",
			"bv_ben_dover_cardinal",
			"bv_ben_dover_dark_green",
			"bv_ben_dover_gold",
			"bv_ben_dover_green",
			"bv_ben_dover_grey",
			"bv_ben_dover_lavender",
			"bv_ben_dover_light_blue",
			"bv_ben_dover_light_yellow",
			"bv_ben_dover_lime",
			"bv_ben_dover_marina_blue",
			"bv_ben_dover_navy_blue",
			"bv_ben_dover_orange",
			"bv_ben_dover_pink",
			"bv_ben_dover_purple",
			"bv_ben_dover_red",
			"bv_ben_dover_sand",
			"bv_ben_dover_silver",
			"bv_ben_dover_skin_blue",
			"bv_ben_dover_skin_camo",
			"bv_ben_dover_skin_camo_urban",
			"bv_caressa_gt_aqua",
			"bv_caressa_gt_baby_blue",
			"bv_caressa_gt_baby_pink",
			"bv_caressa_gt_black2",
			"bv_caressa_gt_burgundy",
			"bv_caressa_gt_cardinal",
			"bv_caressa_gt_dark_green",
			"bv_caressa_gt_gold",
			"bv_caressa_gt_green",
			"bv_caressa_gt_grey",
			"bv_caressa_gt_lavender",
			"bv_caressa_gt_light_blue",
			"bv_caressa_gt_light_yellow",
			"bv_caressa_gt_lime",
			"bv_caressa_gt_marina_blue",
			"bv_caressa_gt_navy_blue",
			"bv_caressa_gt_orange",
			"bv_caressa_gt_pink",
			"bv_caressa_gt_purple",
			"bv_caressa_gt_red",
			"bv_caressa_gt_sand",
			"bv_caressa_gt_silver",
			"bv_caressa_gt_skin_blue",
			"bv_caressa_gt_skin_camo",
			"bv_caressa_gt_skin_camo_urban",
			"bv_e60_m5_aqua",
			"bv_e60_m5_baby_blue",
			"bv_e60_m5_baby_pink",
			"bv_e60_m5_black2",
			"bv_e60_m5_burgundy",
			"bv_e60_m5_cardinal",
			"bv_e60_m5_dark_green",
			"bv_e60_m5_gold",
			"bv_e60_m5_green",
			"bv_e60_m5_grey",
			"bv_e60_m5_lavender",
			"bv_e60_m5_light_blue",
			"bv_e60_m5_light_yellow",
			"bv_e60_m5_lime",
			"bv_e60_m5_marina_blue",
			"bv_e60_m5_navy_blue",
			"bv_e60_m5_orange",
			"bv_e60_m5_pink",
			"bv_e60_m5_purple",
			"bv_e60_m5_red",
			"bv_e60_m5_sand",
			"bv_e60_m5_silver",
			"bv_e60_m5_skin_blue",
			"bv_e60_m5_skin_camo",
			"bv_e60_m5_skin_camo_urban",
			"bv_e63_amg_aqua",
			"bv_e63_amg_baby_blue",
			"bv_e63_amg_baby_pink",
			"bv_e63_amg_black2",
			"bv_e63_amg_burgundy",
			"bv_e63_amg_cardinal",
			"bv_e63_amg_dark_green",
			"bv_e63_amg_gold",
			"bv_e63_amg_green",
			"bv_e63_amg_grey",
			"bv_e63_amg_lavender",
			"bv_e63_amg_light_blue",
			"bv_e63_amg_light_yellow",
			"bv_e63_amg_lime",
			"bv_e63_amg_marina_blue",
			"bv_e63_amg_navy_blue",
			"bv_e63_amg_orange",
			"bv_e63_amg_pink",
			"bv_e63_amg_purple",
			"bv_e63_amg_red",
			"bv_e63_amg_sand",
			"bv_e63_amg_silver",
			"bv_e63_amg_skin_blue",
			"bv_e63_amg_skin_camo",
			"bv_e63_amg_skin_camo_urban",
			"bv_gtr_spec_V_aqua",
			"bv_gtr_spec_V_baby_blue",
			"bv_gtr_spec_V_baby_pink",
			"bv_gtr_spec_V_black2",
			"bv_gtr_spec_V_burgundy",
			"bv_gtr_spec_V_cardinal",
			"bv_gtr_spec_V_dark_green",
			"bv_gtr_spec_V_gold",
			"bv_gtr_spec_V_green",
			"bv_gtr_spec_V_grey",
			"bv_gtr_spec_V_lavender",
			"bv_gtr_spec_V_light_blue",
			"bv_gtr_spec_V_light_yellow",
			"bv_gtr_spec_V_lime",
			"bv_gtr_spec_V_marina_blue",
			"bv_gtr_spec_V_navy_blue",
			"bv_gtr_spec_V_orange",
			"bv_gtr_spec_V_pink",
			"bv_gtr_spec_V_purple",
			"bv_gtr_spec_V_red",
			"bv_gtr_spec_V_sand",
			"bv_gtr_spec_V_silver",
			"bv_gtr_spec_V_skin_blue",
			"bv_gtr_spec_V_skin_camo",
			"bv_gtr_spec_V_skin_camo_urban",
			"bv_shelly_bf_skin",
			"bv_shelly_bw_skin",
			"bv_shelly_rw_skin",
			"bv_shelly_wb_skin",
			"bv_shelly_wbl_skin",
			"bv_shelly_wf_skin",
			"bv_the_crowner_aqua",
			"bv_the_crowner_baby_blue",
			"bv_the_crowner_baby_pink",
			"bv_the_crowner_black2",
			"bv_the_crowner_burgundy",
			"bv_the_crowner_cardinal",
			"bv_the_crowner_dark_green",
			"bv_the_crowner_gold",
			"bv_the_crowner_green",
			"bv_the_crowner_grey",
			"bv_the_crowner_lavender",
			"bv_the_crowner_light_blue",
			"bv_the_crowner_light_yellow",
			"bv_the_crowner_lime",
			"bv_the_crowner_marina_blue",
			"bv_the_crowner_navy_blue",
			"bv_the_crowner_orange",
			"bv_the_crowner_pink",
			"bv_the_crowner_purple",
			"bv_the_crowner_red",
			"bv_the_crowner_sand",
			"bv_the_crowner_silver",
			"bv_the_crowner_skin_blue",
			"bv_the_crowner_skin_camo",
			"bv_the_crowner_skin_camo_urban",
			"bv_the_crowner_skin_white",

	//class FMPTrucks
			"bv_monster_aqua",
			"bv_monster_baby_blue",
			"bv_monster_baby_pink",
			"bv_monster_black2",
			"bv_monster_burgundy",
			"bv_monster_cardinal",
			"bv_monster_dark_green",
			"bv_monster_gold",
			"bv_monster_green",
			"bv_monster_grey",
			"bv_monster_lavender",
			"bv_monster_light_blue",
			"bv_monster_light_yellow",
			"bv_monster_lime",
			"bv_monster_marina_blue",
			"bv_monster_navy_blue",
			"bv_monster_orange",
			"bv_monster_pink",
			"bv_monster_purple",
			"bv_monster_red",
			"bv_monster_sand",
			"bv_monster_silver",
			"bv_monster_skin_blue",
			"bv_monster_skin_camo",
			"bv_monster_skin_camo_urban",
	//class RHSVehicles
			"RHS_BTR70",
			"RHS_BTR70_MSV",
			"RHS_BTR70_VDV",
			"RHS_BTR70_VMF",
			"RHS_BTR70_VV",
			"RHS_BTR80A_MSV",
			"RHS_BTR80A_VDV",
			"RHS_BTR80A_VMF",
			"RHS_BTR80A_VV",
			"RHS_BTR80_MSV",
			"RHS_BTR80_VDV",
			"RHS_BTR80_VMF",
			"RHS_BTR80_VV",
			"RHS_Civ_Truck_02_covered_F",
			"RHS_Civ_Truck_02_transport_F",
			"RHS_M2A3",
			"RHS_M2A3_BUSKI",
			"RHS_UAZ_MSV_01",
			"RHS_Ural_Civ_01",
			"RHS_Ural_Civ_02",
			"RHS_Ural_Civ_03",
			"RHS_Ural_Flat_MSV_01",
			"RHS_Ural_Flat_VDV_01",
			"RHS_Ural_Flat_VMF_01",
			"RHS_Ural_Flat_VV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Fuel_VDV_01",
			"RHS_Ural_Fuel_VMF_01",
			"RHS_Ural_Fuel_VV_01",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_Open_Flat_MSV_01",
			"RHS_Ural_Open_Flat_VDV_01",
			"RHS_Ural_Open_Flat_VMF_01",
			"RHS_Ural_Open_Flat_VV_01",
			"RHS_Ural_Open_MSV_01",
			"RHS_Ural_Open_VDV_01",
			"RHS_Ural_Open_VMF_01",
			"RHS_Ural_Open_VV_01",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Repair_VDV_01",
			"RHS_Ural_Repair_VMF_01",
			"RHS_Ural_Repair_VV_01",
			"RHS_Ural_VDV_01",
			"RHS_Ural_VMF_01",
			"RHS_Ural_VV_01",
			"rhs_bmp3_late_msv",
			"rhs_bmp3mera_msv",
			"rhs_btr60_chdkz",
			"rhs_btr60_vdv",
			"rhs_btr60_vmf",
			"rhs_btr70_chdkz",
			"rhs_gaz66_ammo_msv",
			"rhs_gaz66_ammo_vdv",
			"rhs_gaz66_ammo_vmf",
			"rhs_gaz66_ammo_vv",
			"rhs_gaz66_ap2_msv",
			"rhs_gaz66_ap2_vdv",
			"rhs_gaz66_ap2_vmf",
			"rhs_gaz66_ap2_vv",
			"rhs_gaz66_flat_msv",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66_flat_vmf",
			"rhs_gaz66_flat_vv",
			"rhs_gaz66_msv",
			"rhs_gaz66_r142_msv",
			"rhs_gaz66_r142_vdv",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_r142_vv",
			"rhs_gaz66_repair_msv",
			"rhs_gaz66_repair_vdv",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_repair_vv",
			"rhs_gaz66_vdv",
			"rhs_gaz66_vmf",
			"rhs_gaz66_vv",
			"rhs_gaz66o_flat_msv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66o_flat_vmf",
			"rhs_gaz66o_flat_vv",
			"rhs_gaz66o_msv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_vmf",
			"rhs_gaz66o_vv",
			"rhs_kamaz5350",
			"rhs_kamaz5350_flatbed",
			"rhs_kamaz5350_flatbed_cover",
			"rhs_kamaz5350_flatbed_cover_msv",
			"rhs_kamaz5350_flatbed_cover_vdv",
			"rhs_kamaz5350_flatbed_cover_vmf",
			"rhs_kamaz5350_flatbed_cover_vv",
			"rhs_kamaz5350_flatbed_msv",
			"rhs_kamaz5350_flatbed_vdv",
			"rhs_kamaz5350_flatbed_vmf",
			"rhs_kamaz5350_flatbed_vv",
			"rhs_kamaz5350_msv",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350_open_msv",
			"rhs_kamaz5350_open_vdv",
			"rhs_kamaz5350_open_vmf",
			"rhs_kamaz5350_open_vv",
			"rhs_kamaz5350_vdv",
			"rhs_kamaz5350_vmf",
			"rhs_kamaz5350_vv",
			"rhs_tigr_3camo_vdv",
			"rhs_tigr_3camo_vmf",
			"rhs_tigr_3camo_vv",
			"rhs_tigr_ffv_3camo_msv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_3camo_vmf",
			"rhs_tigr_ffv_3camo_vv",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_ffv_vmf",
			"rhs_tigr_ffv_vv",
			"rhs_tigr_m_3camo_msv",
			"rhs_tigr_m_3camo_vdv",
			"rhs_tigr_m_3camo_vmf",
			"rhs_tigr_m_3camo_vv",
			"rhs_tigr_m_msv",
			"rhs_tigr_m_vdv",
			"rhs_tigr_m_vmf",
			"rhs_tigr_m_vv",
			"rhs_tigr_msv",
			"rhs_tigr_sts_3camo_msv",
			"rhs_tigr_sts_3camo_vdv",
			"rhs_tigr_sts_3camo_vmf",
			"rhs_tigr_sts_3camo_vv",
			"rhs_tigr_sts_msv",
			"rhs_tigr_sts_vdv",
			"rhs_tigr_sts_vmf",
			"rhs_tigr_sts_vv",
			"rhs_tigr_vdv",
			"rhs_tigr_vmf",
			"rhs_tigr_vv",
			"rhs_truck",
			"rhs_typhoon_vdv",
			"rhs_uaz_open_chdkz",
			"rhs_uaz_open_vdv",
			"rhs_uaz_open_vmf",
			"rhs_uaz_open_vv",
			"rhs_uaz_spg9_chdkz",
			"rhs_uaz_vdv",
			"rhs_uaz_vv",
			"rhs_ural_chdkz",
			"rhs_ural_open_chdkz",
			"rhs_ural_work_chdkz",
			"rhs_ural_work_open_chdkz",
			"rhsusf_M1078A1P2_B_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_fmtv_usarmy",
			"rhsusf_M1078A1P2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_fmtv_usarmy",
			"rhsusf_M1083A1P2_open_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_fmtv_usarmy",
			"rhsusf_M1084A1P2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_fmtv_usarmy",
			"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy",
			"rhsusf_M1232_M2_usarmy_d",
			"rhsusf_M1232_M2_usarmy_wd",
			"rhsusf_M1232_MK19_usarmy_d",
			"rhsusf_M1232_MK19_usarmy_wd",
			"rhsusf_M1232_usarmy_d",
			"rhsusf_M1232_usarmy_wd",
			"rhsusf_M1237_M2_usarmy_d",
			"rhsusf_M1237_M2_usarmy_wd",
			"rhsusf_M1237_MK19_usarmy_d",
			"rhsusf_M1237_MK19_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_wd",
			"rhsusf_M977A4_AMMO_usarmy_d",
			"rhsusf_M977A4_AMMO_usarmy_wd",
			"rhsusf_M977A4_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_BKIT_usarmy_d",
			"rhsusf_M977A4_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_usarmy_d",
			"rhsusf_M977A4_REPAIR_usarmy_wd",
			"rhsusf_M977A4_usarmy_d",
			"rhsusf_M977A4_usarmy_wd",
			"rhsusf_M978A4_BKIT_usarmy_d",
			"rhsusf_M978A4_BKIT_usarmy_wd",
			"rhsusf_M978A4_usarmy_d",
			"rhsusf_M978A4_usarmy_wd",
			"rhsusf_m1025_d",
			"rhsusf_m1025_d_Mk19",
			"rhsusf_m1025_d_m2",
			"rhsusf_m1025_d_s",
			"rhsusf_m1025_d_s_Mk19",
			"rhsusf_m1025_d_s_m2",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m1025_w_mk19",
			"rhsusf_m1025_w_s",
			"rhsusf_m1025_w_s_Mk19",
			"rhsusf_m1025_w_s_m2",
			"rhsusf_m113_usarmy_M240",
			"rhsusf_m113_usarmy_MK19",
			"rhsusf_m113_usarmy_supply",
			"rhsusf_m113_usarmy_unarmed",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_M240",
			"rhsusf_m113d_usarmy_MK19",
			"rhsusf_m113d_usarmy_medical",
			"rhsusf_m113d_usarmy_supply",
			"rhsusf_m113d_usarmy_unarmed",
			"rhsusf_m1a1aim_tuski_d",
			"rhsusf_m1a1aim_tuski_wd",
			"rhsusf_m1a1aimd_usarmy",
			"rhsusf_m1a1fep_d",
			"rhsusf_m1a1fep_od",
			"rhsusf_m1a1fep_wd",
			"rhsusf_m1a1hc_wd",
			"rhsusf_m1a2sep1d_usarmy",
			"rhsusf_m1a2sep1tuskid_usarmy",
			"rhsusf_m1a2sep1tuskiid_usarmy",
			"rhsusf_m1a2sep1tuskiiwd_usarmy",
			"rhsusf_m1a2sep1tuskiwd_usarmy",
			"rhsusf_m1a2sep1wd_usarmy",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"rhsusf_m998_d_4dr_fulltop",
			"rhsusf_m998_d_4dr_halftop",
			"rhsusf_m998_d_s_2dr",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_2dr_fulltop",
			"rhsusf_m998_w_2dr_halftop",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_4dr_fulltop",
			"rhsusf_m998_w_4dr_halftop",
			"rhsusf_m998_w_s_2dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_w_s_4dr",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_mrzr4_d",
			"rhsusf_mrzr4_d_mud",
			"rhsusf_mrzr4_w_mud",
			"rhsusf_rg33_d",
			"rhsusf_rg33_m2_usmc_wd",
			"rhsusf_rg33_m2_wd",
			"rhsusf_rg33_usmc_d",
			"rhsusf_rg33_usmc_wd",
			"rhs_sprut_vdv",
			"rhs_2s3_tv",
			"rhs_bmd1_chdkz",
			"rhs_bmd2_chdkz",
			"rhs_bmd4_vdv",
			"rhs_bmd4ma_vdv",
			"rhs_bmd4m_vdv",
			"rhs_bmp1_chdkz",
			"rhs_bmp1d_chdkz",
			"rhs_bmp1k_chdkz",
			"rhs_bmp1p_chdkz",
			"rhs_bmp2e_chdkz",
			"rhs_bmp2_chdkz",
			"rhs_bmp2d_chdkz",
			"rhs_bmp2k_chdkz",
			"rhsusf_m109_usarmy",
			"rhsusf_m109d_usarmy",
			"rhsusf_M1117_W",
			"rhsusf_m113_usarmy",
			"rhsusf_m113_usarmy_M2_90",
			"rhsusf_m113_usarmy_medical",
			"rhsusf_m113_usarmy_MK19_90",
			"rhs_t72bb_chdkz",
			"rhs_t72bb_tv",
			"rhs_t72bd_tv",
			"rhs_t80",
			"rhs_t80a",
			"rhs_t80b",
			"rhs_t80bk",
			"rhs_t80bv",
			"rhs_t80bvk",
			"rhs_t80u45m",
			"rhs_t80u",
			"rhs_t80ue1",
			"rhs_t80uk",
			"rhs_t80um",
			"rhs_t90_tv",
			"rhs_t90a_tv",
			"rhs_zsu234_chdkz",
	//class CUPUnarmed
			"CUP_B_HMMWV_Transport_USA",
			"CUP_B_HMMWV_Unarmed_USA",
			"CUP_B_HMMWV_Unarmed_USMC",
			"CUP_B_LR_Transport_CZ_W",
			"CUP_B_LR_Transport_GB_W",
			"CUP_C_UAZ_Open_TK_CIV",
			"CUP_I_BTR40_TKG",
			"CUP_O_UAZ_Open_RU",
			"CUP_O_UAZ_Unarmed_RU",
			"CUP_O_Ural_Empty_RU",
			"CUP_O_Ural_Open_RU",
			"CUP_O_Ural_RU",
			"CUP_O_Ural_Refuel_RU",
			"CUP_O_Ural_Repair_RU",

	//class CUPArmed
			"CUP_BAF_Jackal2_GMG_W",
			"CUP_BAF_Jackal2_L2A1_W",
			"CUP_B_BAF_Coyote_L2A1_W",
			"CUP_B_Dingo_GER_Wdl",
			"CUP_B_FV432_Bulldog_GB_W_RWS",
			"CUP_B_HMMWV_AGS_GPK_ACR",
			"CUP_B_HMMWV_Crows_M2_USA",
			"CUP_B_HMMWV_Crows_MK19_USA",
			"CUP_B_HMMWV_DSHKM_GPK_ACR",
			"CUP_B_HMMWV_M1114_USMC",
			"CUP_B_HMMWV_M2_GPK_USA",
			"CUP_B_HMMWV_M2_USA",
			"CUP_B_HMMWV_M2_USMC",
			"CUP_B_HMMWV_MK19_USMC",
			"CUP_B_HMMWV_SOV_USA",
			"CUP_B_LAV25M240_USMC",
			"CUP_B_LAV25_HQ_USMC",
			"CUP_B_LAV25_USMC",
			"CUP_B_LR_MG_CZ_W",
			"CUP_B_LR_MG_GB_W",
			"CUP_B_LR_Special_CZ_W",
			"CUP_B_Mastiff_HMG_GB_W",
			"CUP_B_Ridgback_HMG_GB_W",
			"CUP_I_Datsun_PK_Random",
			"CUP_I_SUV_Armored_ION",
			"CUP_I_UAZ_MG_UN",
			"CUP_O_BRDM2_CHDKZ",
			"CUP_O_BRDM2_HQ_CHDKZ",
			"CUP_O_BRDM2_HQ_SLA",
			"CUP_O_BRDM2_SLA",
			"CUP_O_BTR90_HQ_RU",
			"CUP_O_BTR90_RU",
			"CUP_O_Datsun_PK_Random",
			"CUP_O_GAZ_Vodnik_PK_RU",
			"CUP_O_LR_MG_TKA",
			"CUP_O_LR_MG_TKM",
			"CUP_O_UAZ_AGS30_RU",
			"CUP_O_UAZ_MG_RU",

		//Eagel
		"BWA3_Eagle_Fleck",	
		"BWA3_Eagle_FLW100_Fleck",
		"BWA3_Eagle_Tropen",
		"BWA3_Eagle_FLW100_Tropen",	
		"BWA3_Puma_Fleck",	
		"BWA3_Leopard2_Fleck",
		// Tracked vehicles (Tropen)	
		"BWA3_Puma_Tropen",
		"BWA3_Leopard2_Tropen",
		"BW_Offroad_Feldjager_F",
		"BW_Offroad_F",
		"BW_Offroad_Repair_F",
		"BW_SPw_Fennek_Stan_F",
		"BW_SPw_Fennek_SMG_F",
		"BW_SPw_Fennek_Med_F",
		"BW_MATV_Stan_F",
		"BW_MATV_Med_F",
		"BW_LKW7T_Trans_F",
		"BW_LKW7T_Trans_Cov_F",
		"BW_LKW7T_Med_F",
		"BW_LKW7T_Fuel_F",
		"BW_LKW7T_Ammo_F",
		"BW_LKW7T_Repair_F",
		"BW_LKW7T_Device_F",
		"BW_LKW15T_Multi_F",
		"BW_LKW15T_Fuel_F",
		"BW_LKW15T_Ammo_F",
		"BW_LKW15T_Repair_F",
		"BW_Arma_FLW_F",
        //Boats
		//"Exile_Boat_RubberDuck_CSAT",
		//"Exile_Boat_RubberDuck_Digital",
		//"Exile_Boat_RubberDuck_Orange",
		//"Exile_Boat_RubberDuck_Blue",
		//"Exile_Boat_RubberDuck_Black",
		//"Exile_Boat_MotorBoat_Police",
		//"Exile_Boat_MotorBoat_Orange",
		//"Exile_Boat_MotorBoat_White",
		//"Exile_Boat_SDV_CSAT",
		//"Exile_Boat_SDV_Digital",
		//"Exile_Boat_SDV_Grey",
		//"I_Boat_Armed_01_minigun_F",
		//USS Freedom
		//"Land_Carrier_01_base_F",
		//Apex Boat
		//"B_T_Boat_Transport_01_F",
		//"B_T_Lifeboat",
		//"O_T_Lifeboat",
		//"B_T_Boat_Armed_01_minigun_F",
		//"O_T_Boat_Armed_01_hmg_F",
		//"O_T_Boat_Transport_01_F",
		//"I_C_Boat_Transport_01_F",
		//"B_G_Boat_Transport_02_F",
		//"O_G_Boat_Transport_02_F",
		//"I_G_Boat_Transport_02_F",
		//"I_C_Boat_Transport_02_F",
		//"C_Boat_Transport_02_F",
		//"C_Scooter_Transport_01_F",
		//"Burnes_LCAC_1",
		//"Burnes_MK10_1",
		//"sab_boat",
		//"sab_boat_2",
		//"sab_boat_3",
		//"sab_boat_4"	
		//new CONTACT
		//Offroad
		"I_E_Offroad_01_F",
		"I_E_Offroad_01_covered_F",
		"I_E_Offroad_01_comms_F",
		"B_GEN_Offroad_01_covered_F",
		"B_GEN_Offroad_01_comms_F",
		"C_Offroad_01_covered_F",
		"C_Offroad_01_comms_F",
		//Trekker
		"C_Tractor_01_F",
		//Zamak
		"I_E_Truck_02_transport_F",
		"I_E_Truck_02_fuel_F",
		"I_E_Truck_02_Ammo_F",
		"I_E_Truck_02_Box_F",
		"I_E_Truck_02_Medical_F",
		//"I_E_Truck_02_MRL_F",
		//Van
		"I_E_Van_02_vehicle_F",
		"I_E_Van_02_transport_MP_F",
		"I_E_Van_02_medevac_F",
		//"I_E_Heli_light_03_unarmed_F",
		"I_E_APC_tracked_03_cannon_F"	
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	//class SAFArmed
			"rhssaf_army_t72s",
			"rhssaf_m1025_olive_m2",

	//class SAFUnarmed
			"rhssaf_un_ural",
			"rhssaf_un_uaz",
			"rhssaf_un_uaz_open",
			"rhssaf_army_ural",
			"rhssaf_army_ural_open",
			"rhssaf_army_ural_fuel",
			"rhssaf_army_pts",
			"rhssaf_m998_olive_2dr_halftop",
			"rhssaf_m998_olive_2dr_fulltop",
			"rhssaf_m1025_olive",
		//class GREFArmed
			"rhsgref_BRDM2",
			"rhsgref_BRDM2UM",
			"rhsgref_BRDM2UM_b",
			"rhsgref_BRDM2UM_ins",
			"rhsgref_BRDM2UM_ins_g",
			"rhsgref_BRDM2UM_msv",
			"rhsgref_BRDM2UM_vdv",
			"rhsgref_BRDM2UM_vmf",
			"rhsgref_BRDM2_ATGM",
			"rhsgref_BRDM2_ATGM_b",
			"rhsgref_BRDM2_ATGM_ins",
			"rhsgref_BRDM2_ATGM_ins_g",
			"rhsgref_BRDM2_ATGM_msv",
			"rhsgref_BRDM2_ATGM_vdv",
			"rhsgref_BRDM2_ATGM_vmf",
			"rhsgref_BRDM2_HQ",
			"rhsgref_BRDM2_HQ_b",
			"rhsgref_BRDM2_HQ_ins",
			"rhsgref_BRDM2_HQ_ins_g",
			"rhsgref_BRDM2_HQ_msv",
			"rhsgref_BRDM2_HQ_vdv",
			"rhsgref_BRDM2_HQ_vmf",
			"rhsgref_BRDM2_b",
			"rhsgref_BRDM2_ins",
			"rhsgref_BRDM2_ins_g",
			"rhsgref_BRDM2_msv",
			"rhsgref_BRDM2_vdv",
			"rhsgref_BRDM2_vmf",
 			"rhsgref_un_m1117",
	//class GREFUnarmed
 			"rhsgref_cdf_reg_uaz_ags",
 			"rhsgref_cdf_reg_uaz_dshkm",
 			"rhsgref_cdf_reg_uaz_spg9",
	//class HVPCars
	"Mrshounka_corbillard_c",
	"Mrshounka_corbillard_c_bleufonce",
	"Mrshounka_corbillard_c_grise",
	"Mrshounka_corbillard_c_jaune",
	"Mrshounka_corbillard_c_noir",
	"Mrshounka_corbillard_c_orange",
	"Mrshounka_corbillard_c_rose",
	"Mrshounka_corbillard_c_rouge",
	"Mrshounka_corbillard_c_violet",
	"shounka_a3_dafxf_euro6_f",
	"shounka_f430_spider_bleufonce",
	"shounka_f430_spider_grise",
	"shounka_f430_spider_jaune",
	"shounka_f430_spider_noir",
	"shounka_f430_spider_orange",
	"shounka_f430_spider_rose",
	"shounka_f430_spider_rouge",
	"shounka_f430_spider_violet",
	"shounka_ivceco_bleufonce",
	"shounka_ivceco_grise",
	"shounka_ivceco_jaune",
	"shounka_ivceco_noir",
	"shounka_ivceco_orange",
	"shounka_ivceco_rose",
	"shounka_ivceco_rouge",
	"shounka_ivceco_violet",
	"shounka_limo_civ_bleufonce",
	"shounka_limo_civ_grise",
	"shounka_limo_civ_jaune",
	"shounka_limo_civ_noir",
	"shounka_limo_civ_orange",
	"shounka_limo_civ_rose",
	"shounka_limo_civ_violet",
	"Mrshounka_lykan_c_bleufonce",
	"Mrshounka_lykan_c_grise",
	"Mrshounka_lykan_c_jaune",
	"Mrshounka_lykan_c_noir",
	"Mrshounka_lykan_c_orange",
	"Mrshounka_lykan_c_rose",
	"Mrshounka_lykan_c_rouge",
	"Mrshounka_lykan_c_violet",
	"Mrshounka_a3_308_civ_bleufonce",
	"Mrshounka_a3_308_civ_grise",
	"Mrshounka_a3_308_civ_jaune",
	"Mrshounka_a3_308_civ_noir",
	"Mrshounka_a3_308_civ_orange",
	"Mrshounka_a3_308_civ_rose",
	"Mrshounka_a3_308_civ_rouge",
	"Mrshounka_a3_308_civ_violet",
	"SIG_Roadrunner",
	"SIG_Hubcaps",
	"SIG_Magnums",
	"SIG_Hcode",
	"SIG_Superbee",
	"SIG_SuperbeeY",
	"SIG_SuperbeeB",
	"SIG_SuperbeeL",
	"SIG_SuperbeeM",
	"SIG_SuperbeeG",
	"Mr_Own_buggy_bleufonce",
	"Mr_Own_buggy_grise",
	"Mr_Own_buggy_jaune",
	"Mr_Own_buggy_noir",
	"Mr_Own_buggy_orange",
	"Mr_Own_buggy_rose",
	"Mr_Own_buggy_rouge",
	"Mr_Own_buggy_violet",
	"Mr_Own_dodge15_civ",
	"Mr_Own_dodge15_civ_bleufonce",
	"Mr_Own_dodge15_civ_grise",
	"Mr_Own_dodge15_civ_jaune",
	"Mr_Own_dodge15_civ_noir",
	"Mr_Own_dodge15_civ_orange",
	"Mr_Own_dodge15_civ_rose",
	"Mr_Own_dodge15_civ_rouge",
	"Mr_Own_dodge15_civ_violet",
	"Mr_Own_hummer_civ_noir",
	"Mr_Own_hummer_civ_bleufonce",
	"Mr_Own_hummer_civ_grise",
	"Mr_Own_hummer_civ_jaune",
	"Mr_Own_hummer_civ_orange",
	"Mr_Own_hummer_civ_rose",
	"Mr_Own_hummer_civ_violet",
	"Mr_Own_hummer_civ_rouge",
	"shounka_buggy_bleufonce",
	"shounka_buggy_grise",
	"shounka_buggy_jaune",
	"shounka_buggy_noir",
	"shounka_buggy_orange",
	"shounka_buggy_rose",
	"shounka_buggy_rouge",
	"shounka_buggy_violet",
	"shounka_avalanche_bleufonce",
	"shounka_avalanche_grise",
	"shounka_avalanche_jaune",
	"shounka_avalanche_noir",
	"shounka_avalanche_orange",
	"shounka_avalanche_rose",
	"shounka_avalanche_rouge",
	"shounka_avalanche_violet",
	"shounka_monsteur_bleufonce",
	"shounka_monsteur_grise",
	"shounka_monsteur_jaune",
	"shounka_monsteur_noir",
	"shounka_monsteur_orange",
	"shounka_monsteur_rose",
	"shounka_monsteur_rouge",
	"shounka_monsteur_violet",
	"Mrshounka_Vandura_civ",
	"Mrshounka_Vandura_civ_bleufonce",
	"Mrshounka_Vandura_civ_grise",
	"Mrshounka_Vandura_civ_jaune",
	"Mrshounka_Vandura_civ_noir",
	"Mrshounka_Vandura_civ_orange",
	"Mrshounka_Vandura_civ_rose",
	"Mrshounka_Vandura_civ_rouge",
	"Mrshounka_Vandura_civ_violet",
	"Mrshounka_yamaha_p_bf",
	"Mrshounka_yamaha_p_g",
	"Mrshounka_yamaha_p_j",
	"Mrshounka_yamaha_p_noir",
	"Mrshounka_yamaha_p_o",
	"Mrshounka_yamaha_p_rose",
	"Mrshounka_yamaha_p_r",
	"Mrshounka_yamaha_p_v",
	//class FMPCars
			"FMP_Hunter_Alpha",
			"FMP_Hunter_Bgcamo",
			"FMP_Hunter_Grunge",
			"FMP_Hunter_Milsim",
			"FMP_Hunter_Ocamo",
			"FMP_Hunter_Savage",
			"FMP_Hunter_Skull",
			"FMP_Hunter_Suba",
			"FMP_Strider_Carbon",
			"FMP_Strider_Hex",
			"FMP_Strider_Multi",
			"FMP_Strider_Radioactive",
			"FMP_Strider_Rusty",
			"FMP_Strider_Splatter",
			"FMP_Strider_Standard",
			"bv_458_aqua",
			"bv_458_baby_blue",
			"bv_458_baby_pink",
			"bv_458_black2",
			"bv_458_burgundy",
			"bv_458_cardinal",
			"bv_458_dark_green",
			"bv_458_gold",
			"bv_458_green",
			"bv_458_grey",
			"bv_458_lavender",
			"bv_458_light_blue",
			"bv_458_light_yellow",
			"bv_458_lime",
			"bv_458_marina_blue",
			"bv_458_navy_blue",
			"bv_458_orange",
			"bv_458_pink",
			"bv_458_purple",
			"bv_458_red",
			"bv_458_sand",
			"bv_458_silver",
			"bv_458_skin_blue",
			"bv_458_skin_camo",
			"bv_458_skin_camo_urban",
			"bv_ben_dover_aqua",
			"bv_ben_dover_baby_blue",
			"bv_ben_dover_baby_pink",
			"bv_ben_dover_black2",
			"bv_ben_dover_burgundy",
			"bv_ben_dover_cardinal",
			"bv_ben_dover_dark_green",
			"bv_ben_dover_gold",
			"bv_ben_dover_green",
			"bv_ben_dover_grey",
			"bv_ben_dover_lavender",
			"bv_ben_dover_light_blue",
			"bv_ben_dover_light_yellow",
			"bv_ben_dover_lime",
			"bv_ben_dover_marina_blue",
			"bv_ben_dover_navy_blue",
			"bv_ben_dover_orange",
			"bv_ben_dover_pink",
			"bv_ben_dover_purple",
			"bv_ben_dover_red",
			"bv_ben_dover_sand",
			"bv_ben_dover_silver",
			"bv_ben_dover_skin_blue",
			"bv_ben_dover_skin_camo",
			"bv_ben_dover_skin_camo_urban",
			"bv_caressa_gt_aqua",
			"bv_caressa_gt_baby_blue",
			"bv_caressa_gt_baby_pink",
			"bv_caressa_gt_black2",
			"bv_caressa_gt_burgundy",
			"bv_caressa_gt_cardinal",
			"bv_caressa_gt_dark_green",
			"bv_caressa_gt_gold",
			"bv_caressa_gt_green",
			"bv_caressa_gt_grey",
			"bv_caressa_gt_lavender",
			"bv_caressa_gt_light_blue",
			"bv_caressa_gt_light_yellow",
			"bv_caressa_gt_lime",
			"bv_caressa_gt_marina_blue",
			"bv_caressa_gt_navy_blue",
			"bv_caressa_gt_orange",
			"bv_caressa_gt_pink",
			"bv_caressa_gt_purple",
			"bv_caressa_gt_red",
			"bv_caressa_gt_sand",
			"bv_caressa_gt_silver",
			"bv_caressa_gt_skin_blue",
			"bv_caressa_gt_skin_camo",
			"bv_caressa_gt_skin_camo_urban",
			"bv_e60_m5_aqua",
			"bv_e60_m5_baby_blue",
			"bv_e60_m5_baby_pink",
			"bv_e60_m5_black2",
			"bv_e60_m5_burgundy",
			"bv_e60_m5_cardinal",
			"bv_e60_m5_dark_green",
			"bv_e60_m5_gold",
			"bv_e60_m5_green",
			"bv_e60_m5_grey",
			"bv_e60_m5_lavender",
			"bv_e60_m5_light_blue",
			"bv_e60_m5_light_yellow",
			"bv_e60_m5_lime",
			"bv_e60_m5_marina_blue",
			"bv_e60_m5_navy_blue",
			"bv_e60_m5_orange",
			"bv_e60_m5_pink",
			"bv_e60_m5_purple",
			"bv_e60_m5_red",
			"bv_e60_m5_sand",
			"bv_e60_m5_silver",
			"bv_e60_m5_skin_blue",
			"bv_e60_m5_skin_camo",
			"bv_e60_m5_skin_camo_urban",
			"bv_e63_amg_aqua",
			"bv_e63_amg_baby_blue",
			"bv_e63_amg_baby_pink",
			"bv_e63_amg_black2",
			"bv_e63_amg_burgundy",
			"bv_e63_amg_cardinal",
			"bv_e63_amg_dark_green",
			"bv_e63_amg_gold",
			"bv_e63_amg_green",
			"bv_e63_amg_grey",
			"bv_e63_amg_lavender",
			"bv_e63_amg_light_blue",
			"bv_e63_amg_light_yellow",
			"bv_e63_amg_lime",
			"bv_e63_amg_marina_blue",
			"bv_e63_amg_navy_blue",
			"bv_e63_amg_orange",
			"bv_e63_amg_pink",
			"bv_e63_amg_purple",
			"bv_e63_amg_red",
			"bv_e63_amg_sand",
			"bv_e63_amg_silver",
			"bv_e63_amg_skin_blue",
			"bv_e63_amg_skin_camo",
			"bv_e63_amg_skin_camo_urban",
			"bv_gtr_spec_V_aqua",
			"bv_gtr_spec_V_baby_blue",
			"bv_gtr_spec_V_baby_pink",
			"bv_gtr_spec_V_black2",
			"bv_gtr_spec_V_burgundy",
			"bv_gtr_spec_V_cardinal",
			"bv_gtr_spec_V_dark_green",
			"bv_gtr_spec_V_gold",
			"bv_gtr_spec_V_green",
			"bv_gtr_spec_V_grey",
			"bv_gtr_spec_V_lavender",
			"bv_gtr_spec_V_light_blue",
			"bv_gtr_spec_V_light_yellow",
			"bv_gtr_spec_V_lime",
			"bv_gtr_spec_V_marina_blue",
			"bv_gtr_spec_V_navy_blue",
			"bv_gtr_spec_V_orange",
			"bv_gtr_spec_V_pink",
			"bv_gtr_spec_V_purple",
			"bv_gtr_spec_V_red",
			"bv_gtr_spec_V_sand",
			"bv_gtr_spec_V_silver",
			"bv_gtr_spec_V_skin_blue",
			"bv_gtr_spec_V_skin_camo",
			"bv_gtr_spec_V_skin_camo_urban",
			"bv_shelly_bf_skin",
			"bv_shelly_bw_skin",
			"bv_shelly_rw_skin",
			"bv_shelly_wb_skin",
			"bv_shelly_wbl_skin",
			"bv_shelly_wf_skin",
			"bv_the_crowner_aqua",
			"bv_the_crowner_baby_blue",
			"bv_the_crowner_baby_pink",
			"bv_the_crowner_black2",
			"bv_the_crowner_burgundy",
			"bv_the_crowner_cardinal",
			"bv_the_crowner_dark_green",
			"bv_the_crowner_gold",
			"bv_the_crowner_green",
			"bv_the_crowner_grey",
			"bv_the_crowner_lavender",
			"bv_the_crowner_light_blue",
			"bv_the_crowner_light_yellow",
			"bv_the_crowner_lime",
			"bv_the_crowner_marina_blue",
			"bv_the_crowner_navy_blue",
			"bv_the_crowner_orange",
			"bv_the_crowner_pink",
			"bv_the_crowner_purple",
			"bv_the_crowner_red",
			"bv_the_crowner_sand",
			"bv_the_crowner_silver",
			"bv_the_crowner_skin_blue",
			"bv_the_crowner_skin_camo",
			"bv_the_crowner_skin_camo_urban",
			"bv_the_crowner_skin_white",

	//class FMPTrucks
			"bv_monster_aqua",
			"bv_monster_baby_blue",
			"bv_monster_baby_pink",
			"bv_monster_black2",
			"bv_monster_burgundy",
			"bv_monster_cardinal",
			"bv_monster_dark_green",
			"bv_monster_gold",
			"bv_monster_green",
			"bv_monster_grey",
			"bv_monster_lavender",
			"bv_monster_light_blue",
			"bv_monster_light_yellow",
			"bv_monster_lime",
			"bv_monster_marina_blue",
			"bv_monster_navy_blue",
			"bv_monster_orange",
			"bv_monster_pink",
			"bv_monster_purple",
			"bv_monster_red",
			"bv_monster_sand",
			"bv_monster_silver",
			"bv_monster_skin_blue",
			"bv_monster_skin_camo",
			"bv_monster_skin_camo_urban",
	//class RHSVehicles
			"RHS_BTR70",
			"RHS_BTR70_MSV",
			"RHS_BTR70_VDV",
			"RHS_BTR70_VMF",
			"RHS_BTR70_VV",
			"RHS_BTR80A_MSV",
			"RHS_BTR80A_VDV",
			"RHS_BTR80A_VMF",
			"RHS_BTR80A_VV",
			"RHS_BTR80_MSV",
			"RHS_BTR80_VDV",
			"RHS_BTR80_VMF",
			"RHS_BTR80_VV",
			"RHS_Civ_Truck_02_covered_F",
			"RHS_Civ_Truck_02_transport_F",
			"RHS_M2A3",
			"RHS_M2A3_BUSKI",
			"RHS_UAZ_MSV_01",
			"RHS_Ural_Civ_01",
			"RHS_Ural_Civ_02",
			"RHS_Ural_Civ_03",
			"RHS_Ural_Flat_MSV_01",
			"RHS_Ural_Flat_VDV_01",
			"RHS_Ural_Flat_VMF_01",
			"RHS_Ural_Flat_VV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Fuel_VDV_01",
			"RHS_Ural_Fuel_VMF_01",
			"RHS_Ural_Fuel_VV_01",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_Open_Flat_MSV_01",
			"RHS_Ural_Open_Flat_VDV_01",
			"RHS_Ural_Open_Flat_VMF_01",
			"RHS_Ural_Open_Flat_VV_01",
			"RHS_Ural_Open_MSV_01",
			"RHS_Ural_Open_VDV_01",
			"RHS_Ural_Open_VMF_01",
			"RHS_Ural_Open_VV_01",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Repair_VDV_01",
			"RHS_Ural_Repair_VMF_01",
			"RHS_Ural_Repair_VV_01",
			"RHS_Ural_VDV_01",
			"RHS_Ural_VMF_01",
			"RHS_Ural_VV_01",
			"rhs_bmp3_late_msv",
			"rhs_bmp3mera_msv",
			"rhs_btr60_chdkz",
			"rhs_btr60_vdv",
			"rhs_btr60_vmf",
			"rhs_btr70_chdkz",
			"rhs_gaz66_ammo_msv",
			"rhs_gaz66_ammo_vdv",
			"rhs_gaz66_ammo_vmf",
			"rhs_gaz66_ammo_vv",
			"rhs_gaz66_ap2_msv",
			"rhs_gaz66_ap2_vdv",
			"rhs_gaz66_ap2_vmf",
			"rhs_gaz66_ap2_vv",
			"rhs_gaz66_flat_msv",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66_flat_vmf",
			"rhs_gaz66_flat_vv",
			"rhs_gaz66_msv",
			"rhs_gaz66_r142_msv",
			"rhs_gaz66_r142_vdv",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_r142_vv",
			"rhs_gaz66_repair_msv",
			"rhs_gaz66_repair_vdv",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_repair_vv",
			"rhs_gaz66_vdv",
			"rhs_gaz66_vmf",
			"rhs_gaz66_vv",
			"rhs_gaz66o_flat_msv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66o_flat_vmf",
			"rhs_gaz66o_flat_vv",
			"rhs_gaz66o_msv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_vmf",
			"rhs_gaz66o_vv",
			"rhs_kamaz5350",
			"rhs_kamaz5350_flatbed",
			"rhs_kamaz5350_flatbed_cover",
			"rhs_kamaz5350_flatbed_cover_msv",
			"rhs_kamaz5350_flatbed_cover_vdv",
			"rhs_kamaz5350_flatbed_cover_vmf",
			"rhs_kamaz5350_flatbed_cover_vv",
			"rhs_kamaz5350_flatbed_msv",
			"rhs_kamaz5350_flatbed_vdv",
			"rhs_kamaz5350_flatbed_vmf",
			"rhs_kamaz5350_flatbed_vv",
			"rhs_kamaz5350_msv",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350_open_msv",
			"rhs_kamaz5350_open_vdv",
			"rhs_kamaz5350_open_vmf",
			"rhs_kamaz5350_open_vv",
			"rhs_kamaz5350_vdv",
			"rhs_kamaz5350_vmf",
			"rhs_kamaz5350_vv",
			"rhs_tigr_3camo_vdv",
			"rhs_tigr_3camo_vmf",
			"rhs_tigr_3camo_vv",
			"rhs_tigr_ffv_3camo_msv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_3camo_vmf",
			"rhs_tigr_ffv_3camo_vv",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_ffv_vmf",
			"rhs_tigr_ffv_vv",
			"rhs_tigr_m_3camo_msv",
			"rhs_tigr_m_3camo_vdv",
			"rhs_tigr_m_3camo_vmf",
			"rhs_tigr_m_3camo_vv",
			"rhs_tigr_m_msv",
			"rhs_tigr_m_vdv",
			"rhs_tigr_m_vmf",
			"rhs_tigr_m_vv",
			"rhs_tigr_msv",
			"rhs_tigr_sts_3camo_msv",
			"rhs_tigr_sts_3camo_vdv",
			"rhs_tigr_sts_3camo_vmf",
			"rhs_tigr_sts_3camo_vv",
			"rhs_tigr_sts_msv",
			"rhs_tigr_sts_vdv",
			"rhs_tigr_sts_vmf",
			"rhs_tigr_sts_vv",
			"rhs_tigr_vdv",
			"rhs_tigr_vmf",
			"rhs_tigr_vv",
			"rhs_truck",
			"rhs_typhoon_vdv",
			"rhs_uaz_open_chdkz",
			"rhs_uaz_open_vdv",
			"rhs_uaz_open_vmf",
			"rhs_uaz_open_vv",
			"rhs_uaz_spg9_chdkz",
			"rhs_uaz_vdv",
			"rhs_uaz_vv",
			"rhs_ural_chdkz",
			"rhs_ural_open_chdkz",
			"rhs_ural_work_chdkz",
			"rhs_ural_work_open_chdkz",
			"rhsusf_M1078A1P2_B_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_fmtv_usarmy",
			"rhsusf_M1078A1P2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_fmtv_usarmy",
			"rhsusf_M1083A1P2_open_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_fmtv_usarmy",
			"rhsusf_M1084A1P2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_fmtv_usarmy",
			"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy",
			"rhsusf_M1232_M2_usarmy_d",
			"rhsusf_M1232_M2_usarmy_wd",
			"rhsusf_M1232_MK19_usarmy_d",
			"rhsusf_M1232_MK19_usarmy_wd",
			"rhsusf_M1232_usarmy_d",
			"rhsusf_M1232_usarmy_wd",
			"rhsusf_M1237_M2_usarmy_d",
			"rhsusf_M1237_M2_usarmy_wd",
			"rhsusf_M1237_MK19_usarmy_d",
			"rhsusf_M1237_MK19_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_wd",
			"rhsusf_M977A4_AMMO_usarmy_d",
			"rhsusf_M977A4_AMMO_usarmy_wd",
			"rhsusf_M977A4_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_BKIT_usarmy_d",
			"rhsusf_M977A4_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_usarmy_d",
			"rhsusf_M977A4_REPAIR_usarmy_wd",
			"rhsusf_M977A4_usarmy_d",
			"rhsusf_M977A4_usarmy_wd",
			"rhsusf_M978A4_BKIT_usarmy_d",
			"rhsusf_M978A4_BKIT_usarmy_wd",
			"rhsusf_M978A4_usarmy_d",
			"rhsusf_M978A4_usarmy_wd",
			"rhsusf_m1025_d",
			"rhsusf_m1025_d_Mk19",
			"rhsusf_m1025_d_m2",
			"rhsusf_m1025_d_s",
			"rhsusf_m1025_d_s_Mk19",
			"rhsusf_m1025_d_s_m2",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m1025_w_mk19",
			"rhsusf_m1025_w_s",
			"rhsusf_m1025_w_s_Mk19",
			"rhsusf_m1025_w_s_m2",
			"rhsusf_m113_usarmy_M240",
			"rhsusf_m113_usarmy_MK19",
			"rhsusf_m113_usarmy_supply",
			"rhsusf_m113_usarmy_unarmed",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_M240",
			"rhsusf_m113d_usarmy_MK19",
			"rhsusf_m113d_usarmy_medical",
			"rhsusf_m113d_usarmy_supply",
			"rhsusf_m113d_usarmy_unarmed",
			"rhsusf_m1a1aim_tuski_d",
			"rhsusf_m1a1aim_tuski_wd",
			"rhsusf_m1a1aimd_usarmy",
			"rhsusf_m1a1fep_d",
			"rhsusf_m1a1fep_od",
			"rhsusf_m1a1fep_wd",
			"rhsusf_m1a1hc_wd",
			"rhsusf_m1a2sep1d_usarmy",
			"rhsusf_m1a2sep1tuskid_usarmy",
			"rhsusf_m1a2sep1tuskiid_usarmy",
			"rhsusf_m1a2sep1tuskiiwd_usarmy",
			"rhsusf_m1a2sep1tuskiwd_usarmy",
			"rhsusf_m1a2sep1wd_usarmy",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"rhsusf_m998_d_4dr_fulltop",
			"rhsusf_m998_d_4dr_halftop",
			"rhsusf_m998_d_s_2dr",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_2dr_fulltop",
			"rhsusf_m998_w_2dr_halftop",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_4dr_fulltop",
			"rhsusf_m998_w_4dr_halftop",
			"rhsusf_m998_w_s_2dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_w_s_4dr",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_mrzr4_d",
			"rhsusf_mrzr4_d_mud",
			"rhsusf_mrzr4_w_mud",
			"rhsusf_rg33_d",
			"rhsusf_rg33_m2_usmc_wd",
			"rhsusf_rg33_m2_wd",
			"rhsusf_rg33_usmc_d",
			"rhsusf_rg33_usmc_wd",
			"rhs_sprut_vdv",
			"rhs_2s3_tv",
			"rhs_bmd1_chdkz",
			"rhs_bmd2_chdkz",
			"rhs_bmd4_vdv",
			"rhs_bmd4ma_vdv",
			"rhs_bmd4m_vdv",
			"rhs_bmp1_chdkz",
			"rhs_bmp1d_chdkz",
			"rhs_bmp1k_chdkz",
			"rhs_bmp1p_chdkz",
			"rhs_bmp2e_chdkz",
			"rhs_bmp2_chdkz",
			"rhs_bmp2d_chdkz",
			"rhs_bmp2k_chdkz",
			"rhsusf_m109_usarmy",
			"rhsusf_m109d_usarmy",
			"rhsusf_M1117_W",
			"rhsusf_m113_usarmy",
			"rhsusf_m113_usarmy_M2_90",
			"rhsusf_m113_usarmy_medical",
			"rhsusf_m113_usarmy_MK19_90",
			"rhs_t72bb_chdkz",
			"rhs_t72bb_tv",
			"rhs_t72bd_tv",
			"rhs_t80",
			"rhs_t80a",
			"rhs_t80b",
			"rhs_t80bk",
			"rhs_t80bv",
			"rhs_t80bvk",
			"rhs_t80u45m",
			"rhs_t80u",
			"rhs_t80ue1",
			"rhs_t80uk",
			"rhs_t80um",
			"rhs_t90_tv",
			"rhs_t90a_tv",
			"rhs_zsu234_chdkz",
	//class CUPUnarmed
			"CUP_B_HMMWV_Transport_USA",
			"CUP_B_HMMWV_Unarmed_USA",
			"CUP_B_HMMWV_Unarmed_USMC",
			"CUP_B_LR_Transport_CZ_W",
			"CUP_B_LR_Transport_GB_W",
			"CUP_C_UAZ_Open_TK_CIV",
			"CUP_I_BTR40_TKG",
			"CUP_O_UAZ_Open_RU",
			"CUP_O_UAZ_Unarmed_RU",
			"CUP_O_Ural_Empty_RU",
			"CUP_O_Ural_Open_RU",
			"CUP_O_Ural_RU",
			"CUP_O_Ural_Refuel_RU",
			"CUP_O_Ural_Repair_RU",

	//class CUPArmed
			"CUP_BAF_Jackal2_GMG_W",
			"CUP_BAF_Jackal2_L2A1_W",
			"CUP_B_BAF_Coyote_L2A1_W",
			"CUP_B_Dingo_GER_Wdl",
			"CUP_B_FV432_Bulldog_GB_W_RWS",
			"CUP_B_HMMWV_AGS_GPK_ACR",
			"CUP_B_HMMWV_Crows_M2_USA",
			"CUP_B_HMMWV_Crows_MK19_USA",
			"CUP_B_HMMWV_DSHKM_GPK_ACR",
			"CUP_B_HMMWV_M1114_USMC",
			"CUP_B_HMMWV_M2_GPK_USA",
			"CUP_B_HMMWV_M2_USA",
			"CUP_B_HMMWV_M2_USMC",
			"CUP_B_HMMWV_MK19_USMC",
			"CUP_B_HMMWV_SOV_USA",
			"CUP_B_LAV25M240_USMC",
			"CUP_B_LAV25_HQ_USMC",
			"CUP_B_LAV25_USMC",
			"CUP_B_LR_MG_CZ_W",
			"CUP_B_LR_MG_GB_W",
			"CUP_B_LR_Special_CZ_W",
			"CUP_B_Mastiff_HMG_GB_W",
			"CUP_B_Ridgback_HMG_GB_W",
			"CUP_I_Datsun_PK_Random",
			"CUP_I_SUV_Armored_ION",
			"CUP_I_UAZ_MG_UN",
			"CUP_O_BRDM2_CHDKZ",
			"CUP_O_BRDM2_HQ_CHDKZ",
			"CUP_O_BRDM2_HQ_SLA",
			"CUP_O_BRDM2_SLA",
			"CUP_O_BTR90_HQ_RU",
			"CUP_O_BTR90_RU",
			"CUP_O_Datsun_PK_Random",
			"CUP_O_GAZ_Vodnik_PK_RU",
			"CUP_O_LR_MG_TKA",
			"CUP_O_LR_MG_TKM",
			"CUP_O_UAZ_AGS30_RU",
			"CUP_O_UAZ_MG_RU",

		//Eagel
		"BWA3_Eagle_Fleck",	
		"BWA3_Eagle_FLW100_Fleck",
		"BWA3_Eagle_Tropen",
		"BWA3_Eagle_FLW100_Tropen",	
		//"BWA3_Puma_Fleck",	
		//"BWA3_Leopard2_Fleck",
		// Tracked vehicles (Tropen)	
		//"BWA3_Puma_Tropen",
		//"BWA3_Leopard2_Tropen",
		"BW_Offroad_Feldjager_F",
		"BW_Offroad_F",
		"BW_Offroad_Repair_F",
		"BW_SPw_Fennek_Stan_F",
		"BW_SPw_Fennek_SMG_F",
		"BW_SPw_Fennek_Med_F",
		"BW_MATV_Stan_F",
		"BW_MATV_Med_F",
		"BW_LKW7T_Trans_F",
		"BW_LKW7T_Trans_Cov_F",
		"BW_LKW7T_Med_F",
		"BW_LKW7T_Fuel_F",
		//"BW_LKW7T_Ammo_F",
		"BW_LKW7T_Repair_F",
		"BW_LKW7T_Device_F",
		"BW_LKW15T_Multi_F",
		"BW_LKW15T_Fuel_F",
		//"BW_LKW15T_Ammo_F",
		"BW_LKW15T_Repair_F",
		"BW_Arma_FLW_F",
	//class CUPBoats

			"CUP_C_Fishing_Boat_Chernarus",
			"CUP_B_RHIB2Turret_USMC",
			"CUP_B_Seafox_USMC",
			"CUP_B_Seafox_USV_USMC",
			"CUP_B_Zodiac_USMC",	
	//class RHSBoats
			"rhsusf_mkvsoc",			
    //Boats
		"Exile_Boat_RubberDuck_CSAT",
		"Exile_Boat_RubberDuck_Digital",
		"Exile_Boat_RubberDuck_Orange",
		"Exile_Boat_RubberDuck_Blue",
		"Exile_Boat_RubberDuck_Black",
		"Exile_Boat_MotorBoat_Police",
		"Exile_Boat_MotorBoat_Orange",
		"Exile_Boat_MotorBoat_White",
		"Exile_Boat_SDV_CSAT",
		"Exile_Boat_SDV_Digital",
		"Exile_Boat_SDV_Grey",
		"I_Boat_Armed_01_minigun_F",
		//USS Freedom
		//"Land_Carrier_01_base_F",
		//Apex Boat
		"B_T_Boat_Transport_01_F",
		"B_T_Lifeboat",
		"O_T_Lifeboat",
		"B_T_Boat_Armed_01_minigun_F",
		"O_T_Boat_Armed_01_hmg_F",
		"O_T_Boat_Transport_01_F",
		"I_C_Boat_Transport_01_F",
		"B_G_Boat_Transport_02_F",
		"O_G_Boat_Transport_02_F",
		"I_G_Boat_Transport_02_F",
		"I_C_Boat_Transport_02_F",
		"C_Boat_Transport_02_F",
		"C_Scooter_Transport_01_F",
		//new CONTACT
		//Offroad
		"I_E_Offroad_01_F",
		"I_E_Offroad_01_covered_F",
		"I_E_Offroad_01_comms_F",
		"B_GEN_Offroad_01_covered_F",
		"B_GEN_Offroad_01_comms_F",
		"C_Offroad_01_covered_F",
		"C_Offroad_01_comms_F",
		//Trekker
		"C_Tractor_01_F",
		//Zamak
		"I_E_Truck_02_transport_F",
		"I_E_Truck_02_fuel_F",
		//"I_E_Truck_02_Ammo_F",
		"I_E_Truck_02_Box_F",
		"I_E_Truck_02_Medical_F",
		//"I_E_Truck_02_MRL_F",
		//Van
		"I_E_Van_02_vehicle_F",
		"I_E_Van_02_transport_MP_F",
		"I_E_Van_02_medevac_F"
		//"I_E_Heli_light_03_unarmed_F",
		//"I_E_APC_tracked_03_cannon_F"	
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[

];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	//class SAFArmed
		["rhssaf_army_t72s", 25],
		["rhssaf_m1025_olive_m2", 25],

	//class SAFUnarmed
		["rhssaf_un_ural", 25],
		["rhssaf_un_uaz", 25],
		["rhssaf_un_uaz_open", 25],
		["rhssaf_army_ural", 25],
		["rhssaf_army_ural_open", 25],
		["rhssaf_army_ural_fuel", 25],
		["rhssaf_army_pts", 25],
		["rhssaf_m998_olive_2dr_halftop", 25],
		["rhssaf_m998_olive_2dr_fulltop", 25],
		["rhssaf_m1025_olive", 25],

	//class SAFChoppers
 		["rhssaf_airforce_ht48", 25],
		//class GREFArmed
		["rhsgref_BRDM2", 25],
		["rhsgref_BRDM2UM", 25],
		["rhsgref_BRDM2UM_b", 25],
		["rhsgref_BRDM2UM_ins", 25],
		["rhsgref_BRDM2UM_ins_g", 25],
		["rhsgref_BRDM2UM_msv", 25],
		["rhsgref_BRDM2UM_vdv", 25],
		["rhsgref_BRDM2UM_vmf", 25],
		["rhsgref_BRDM2_ATGM", 25],
		["rhsgref_BRDM2_ATGM_b", 25],
		["rhsgref_BRDM2_ATGM_ins", 25],
		["rhsgref_BRDM2_ATGM_ins_g", 25],
		["rhsgref_BRDM2_ATGM_msv", 25],
		["rhsgref_BRDM2_ATGM_vdv", 25],
		["rhsgref_BRDM2_ATGM_vmf", 25],
		["rhsgref_BRDM2_HQ", 25],
		["rhsgref_BRDM2_HQ_b", 25],
		["rhsgref_BRDM2_HQ_ins", 25],
		["rhsgref_BRDM2_HQ_ins_g", 25],
		["rhsgref_BRDM2_HQ_msv", 25],
		["rhsgref_BRDM2_HQ_vdv", 25],
		["rhsgref_BRDM2_HQ_vmf", 25],
		["rhsgref_BRDM2_b", 25],
		["rhsgref_BRDM2_ins", 25],
		["rhsgref_BRDM2_ins_g", 25],
		["rhsgref_BRDM2_msv", 25],
		["rhsgref_BRDM2_vdv", 25],
		["rhsgref_BRDM2_vmf", 25],
 		["rhsgref_un_m1117", 25],
	//class GREFUnarmed
 		["rhsgref_cdf_reg_uaz_ags", 25],
 		["rhsgref_cdf_reg_uaz_dshkm", 25],
 		["rhsgref_cdf_reg_uaz_spg9", 25],

	//class GREFChoppers
			["rhsgref_mi24g_CAS", 25],
			["rhsgref_mi24g_FAB", 25],
			["rhsgref_mi24g_UPK23", 25],

	//class GREFPlanes
 		["RHS_AN2", 25],
 		["rhs_l159_CDF", 25],
 		["rhs_l159_CDF_CAP", 25],
 		["rhs_l159_CDF_CAS", 25],
 		["rhs_l159_CDF_plamen", 25],
 		["rhs_l39_cdf", 25],
	//class HVPCars
		["Mrshounka_corbillard_c", 25],
		["Mrshounka_corbillard_c_bleufonce", 25],
		["Mrshounka_corbillard_c_grise", 25],
		["Mrshounka_corbillard_c_jaune", 25],
		["Mrshounka_corbillard_c_noir", 25],
		["Mrshounka_corbillard_c_orange", 25],
		["Mrshounka_corbillard_c_rose", 25],
		["Mrshounka_corbillard_c_rouge", 25],
		["Mrshounka_corbillard_c_violet", 25],
		["shounka_a3_dafxf_euro6_f", 25],
		["shounka_f430_spider_bleufonce", 25],
		["shounka_f430_spider_grise", 25],
		["shounka_f430_spider_jaune", 25],
		["shounka_f430_spider_noir", 25],
		["shounka_f430_spider_orange", 25],
		["shounka_f430_spider_rose", 25],
		["shounka_f430_spider_rouge", 25],
		["shounka_f430_spider_violet", 25],
		["shounka_ivceco_bleufonce", 25],
		["shounka_ivceco_grise", 25],
		["shounka_ivceco_jaune", 25],
		["shounka_ivceco_noir", 25],
		["shounka_ivceco_orange", 25],
		["shounka_ivceco_rose", 25],
		["shounka_ivceco_rouge", 25],
		["shounka_ivceco_violet", 25],
		["shounka_limo_civ_bleufonce", 25],
		["shounka_limo_civ_grise", 25],
		["shounka_limo_civ_jaune", 25],
		["shounka_limo_civ_noir", 25],
		["shounka_limo_civ_orange", 25],
		["shounka_limo_civ_rose", 25],
		["shounka_limo_civ_violet", 25],
		["Mrshounka_lykan_c_bleufonce", 25],
		["Mrshounka_lykan_c_grise", 25],
		["Mrshounka_lykan_c_jaune", 25],
		["Mrshounka_lykan_c_noir", 25],
		["Mrshounka_lykan_c_orange", 25],
		["Mrshounka_lykan_c_rose", 25],
		["Mrshounka_lykan_c_rouge", 25],
		["Mrshounka_lykan_c_violet", 25],
		["Mrshounka_a3_308_civ_bleufonce", 25],
		["Mrshounka_a3_308_civ_grise", 25],
		["Mrshounka_a3_308_civ_jaune", 25],
		["Mrshounka_a3_308_civ_noir", 25],
		["Mrshounka_a3_308_civ_orange", 25],
		["Mrshounka_a3_308_civ_rose", 25],
		["Mrshounka_a3_308_civ_rouge", 25],
		["Mrshounka_a3_308_civ_violet", 25],
		["SIG_Roadrunner", 25],
		["SIG_Hubcaps", 25],
		["SIG_Magnums", 25],
		["SIG_Hcode", 25],
		["SIG_Superbee", 25],
		["SIG_SuperbeeY", 25],
		["SIG_SuperbeeB", 25],
		["SIG_SuperbeeL", 25],
		["SIG_SuperbeeM", 25],
		["SIG_SuperbeeG", 25],
		["Mr_Own_buggy_bleufonce", 25],
		["Mr_Own_buggy_grise", 25],
		["Mr_Own_buggy_jaune", 25],
		["Mr_Own_buggy_noir", 25],
		["Mr_Own_buggy_orange", 25],
		["Mr_Own_buggy_rose", 25],
		["Mr_Own_buggy_rouge", 25],
		["Mr_Own_buggy_violet", 25],
		["Mr_Own_dodge15_civ", 25],
		["Mr_Own_dodge15_civ_bleufonce", 25],
		["Mr_Own_dodge15_civ_grise", 25],
		["Mr_Own_dodge15_civ_jaune", 25],
		["Mr_Own_dodge15_civ_noir", 25],
		["Mr_Own_dodge15_civ_orange", 25],
		["Mr_Own_dodge15_civ_rose", 25],
		["Mr_Own_dodge15_civ_rouge", 25],
		["Mr_Own_dodge15_civ_violet", 25],
		["Mr_Own_hummer_civ_noir", 25],
		["Mr_Own_hummer_civ_bleufonce", 25],
		["Mr_Own_hummer_civ_grise", 25],
		["Mr_Own_hummer_civ_jaune", 25],
		["Mr_Own_hummer_civ_orange", 25],
		["Mr_Own_hummer_civ_rose", 25],
		["Mr_Own_hummer_civ_violet", 25],
		["Mr_Own_hummer_civ_rouge", 25],
		["shounka_buggy_bleufonce", 25],
		["shounka_buggy_grise", 25],
		["shounka_buggy_jaune", 25],
		["shounka_buggy_noir", 25],
		["shounka_buggy_orange", 25],
		["shounka_buggy_rose", 25],
		["shounka_buggy_rouge", 25],
		["shounka_buggy_violet", 25],
		["shounka_avalanche_bleufonce", 25],
		["shounka_avalanche_grise", 25],
		["shounka_avalanche_jaune", 25],
		["shounka_avalanche_noir", 25],
		["shounka_avalanche_orange", 25],
		["shounka_avalanche_rose", 25],
		["shounka_avalanche_rouge", 25],
		["shounka_avalanche_violet", 25],
		["shounka_monsteur_bleufonce", 25],
		["shounka_monsteur_grise", 25],
		["shounka_monsteur_jaune", 25],
		["shounka_monsteur_noir", 25],
		["shounka_monsteur_orange", 25],
		["shounka_monsteur_rose", 25],
		["shounka_monsteur_rouge", 25],
		["shounka_monsteur_violet", 25],
		["Mrshounka_Vandura_civ", 25],
		["Mrshounka_Vandura_civ_bleufonce", 25],
		["Mrshounka_Vandura_civ_grise", 25],
		["Mrshounka_Vandura_civ_jaune", 25],
		["Mrshounka_Vandura_civ_noir", 25],
		["Mrshounka_Vandura_civ_orange", 25],
		["Mrshounka_Vandura_civ_rose", 25],
		["Mrshounka_Vandura_civ_rouge", 25],
		["Mrshounka_Vandura_civ_violet", 25],
		["Mrshounka_yamaha_p_bf", 25],
		["Mrshounka_yamaha_p_g", 25],
		["Mrshounka_yamaha_p_j", 25],
		["Mrshounka_yamaha_p_noir", 25],
		["Mrshounka_yamaha_p_o", 25],
		["Mrshounka_yamaha_p_rose", 25],
		["Mrshounka_yamaha_p_r", 25],
		["Mrshounka_yamaha_p_v", 25],
	//class HVPPlanes
		["sab_camel_blu", 25],
		["sab_camel_red", 25],
		["MV22", 25],
	//class FMPCars
		["FMP_Hunter_Alpha", 25],
		["FMP_Hunter_Bgcamo", 25],
		["FMP_Hunter_Grunge", 25],
		["FMP_Hunter_Milsim", 25],
		["FMP_Hunter_Ocamo", 25],
		["FMP_Hunter_Savage", 25],
		["FMP_Hunter_Skull", 25],
		["FMP_Hunter_Suba", 25],
		["FMP_Strider_Carbon", 25],
		["FMP_Strider_Hex", 25],
		["FMP_Strider_Multi", 25],
		["FMP_Strider_Radioactive", 25],
		["FMP_Strider_Rusty", 25],
		["FMP_Strider_Splatter", 25],
		["FMP_Strider_Standard", 25],
		["bv_458_aqua", 25],
		["bv_458_baby_blue", 25],
		["bv_458_baby_pink", 25],
		["bv_458_black2", 25],
		["bv_458_burgundy", 25],
		["bv_458_cardinal", 25],
		["bv_458_dark_green", 25],
		["bv_458_gold", 25],
		["bv_458_green", 25],
		["bv_458_grey", 25],
		["bv_458_lavender", 25],
		["bv_458_light_blue", 25],
		["bv_458_light_yellow", 25],
		["bv_458_lime", 25],
		["bv_458_marina_blue", 25],
		["bv_458_navy_blue", 25],
		["bv_458_orange", 25],
		["bv_458_pink", 25],
		["bv_458_purple", 25],
		["bv_458_red", 25],
		["bv_458_sand", 25],
		["bv_458_silver", 25],
		["bv_458_skin_blue", 25],
		["bv_458_skin_camo", 25],
		["bv_458_skin_camo_urban", 25],
		["bv_ben_dover_aqua", 25],
		["bv_ben_dover_baby_blue", 25],
		["bv_ben_dover_baby_pink", 25],
		["bv_ben_dover_black2", 25],
		["bv_ben_dover_burgundy", 25],
		["bv_ben_dover_cardinal", 25],
		["bv_ben_dover_dark_green", 25],
		["bv_ben_dover_gold", 25],
		["bv_ben_dover_green", 25],
		["bv_ben_dover_grey", 25],
		["bv_ben_dover_lavender", 25],
		["bv_ben_dover_light_blue", 25],
		["bv_ben_dover_light_yellow", 25],
		["bv_ben_dover_lime", 25],
		["bv_ben_dover_marina_blue", 25],
		["bv_ben_dover_navy_blue", 25],
		["bv_ben_dover_orange", 25],
		["bv_ben_dover_pink", 25],
		["bv_ben_dover_purple", 25],
		["bv_ben_dover_red", 25],
		["bv_ben_dover_sand", 25],
		["bv_ben_dover_silver", 25],
		["bv_ben_dover_skin_blue", 25],
		["bv_ben_dover_skin_camo", 25],
		["bv_ben_dover_skin_camo_urban", 25],
		["bv_caressa_gt_aqua", 25],
		["bv_caressa_gt_baby_blue", 25],
		["bv_caressa_gt_baby_pink", 25],
		["bv_caressa_gt_black2", 25],
		["bv_caressa_gt_burgundy", 25],
		["bv_caressa_gt_cardinal", 25],
		["bv_caressa_gt_dark_green", 25],
		["bv_caressa_gt_gold", 25],
		["bv_caressa_gt_green", 25],
		["bv_caressa_gt_grey", 25],
		["bv_caressa_gt_lavender", 25],
		["bv_caressa_gt_light_blue", 25],
		["bv_caressa_gt_light_yellow", 25],
		["bv_caressa_gt_lime", 25],
		["bv_caressa_gt_marina_blue", 25],
		["bv_caressa_gt_navy_blue", 25],
		["bv_caressa_gt_orange", 25],
		["bv_caressa_gt_pink", 25],
		["bv_caressa_gt_purple", 25],
		["bv_caressa_gt_red", 25],
		["bv_caressa_gt_sand", 25],
		["bv_caressa_gt_silver", 25],
		["bv_caressa_gt_skin_blue", 25],
		["bv_caressa_gt_skin_camo", 25],
		["bv_caressa_gt_skin_camo_urban", 25],
		["bv_e60_m5_aqua", 25],
		["bv_e60_m5_baby_blue", 25],
		["bv_e60_m5_baby_pink", 25],
		["bv_e60_m5_black2", 25],
		["bv_e60_m5_burgundy", 25],
		["bv_e60_m5_cardinal", 25],
		["bv_e60_m5_dark_green", 25],
		["bv_e60_m5_gold", 25],
		["bv_e60_m5_green", 25],
		["bv_e60_m5_grey", 25],
		["bv_e60_m5_lavender", 25],
		["bv_e60_m5_light_blue", 25],
		["bv_e60_m5_light_yellow", 25],
		["bv_e60_m5_lime", 25],
		["bv_e60_m5_marina_blue", 25],
		["bv_e60_m5_navy_blue", 25],
		["bv_e60_m5_orange", 25],
		["bv_e60_m5_pink", 25],
		["bv_e60_m5_purple", 25],
		["bv_e60_m5_red", 25],
		["bv_e60_m5_sand", 25],
		["bv_e60_m5_silver", 25],
		["bv_e60_m5_skin_blue", 25],
		["bv_e60_m5_skin_camo", 25],
		["bv_e60_m5_skin_camo_urban", 25],
		["bv_e63_amg_aqua", 25],
		["bv_e63_amg_baby_blue", 25],
		["bv_e63_amg_baby_pink", 25],
		["bv_e63_amg_black2", 25],
		["bv_e63_amg_burgundy", 25],
		["bv_e63_amg_cardinal", 25],
		["bv_e63_amg_dark_green", 25],
		["bv_e63_amg_gold", 25],
		["bv_e63_amg_green", 25],
		["bv_e63_amg_grey", 25],
		["bv_e63_amg_lavender", 25],
		["bv_e63_amg_light_blue", 25],
		["bv_e63_amg_light_yellow", 25],
		["bv_e63_amg_lime", 25],
		["bv_e63_amg_marina_blue", 25],
		["bv_e63_amg_navy_blue", 25],
		["bv_e63_amg_orange", 25],
		["bv_e63_amg_pink", 25],
		["bv_e63_amg_purple", 25],
		["bv_e63_amg_red", 25],
		["bv_e63_amg_sand", 25],
		["bv_e63_amg_silver", 25],
		["bv_e63_amg_skin_blue", 25],
		["bv_e63_amg_skin_camo", 25],
		["bv_e63_amg_skin_camo_urban", 25],
		["bv_gtr_spec_V_aqua", 25],
		["bv_gtr_spec_V_baby_blue", 25],
		["bv_gtr_spec_V_baby_pink", 25],
		["bv_gtr_spec_V_black2", 25],
		["bv_gtr_spec_V_burgundy", 25],
		["bv_gtr_spec_V_cardinal", 25],
		["bv_gtr_spec_V_dark_green", 25],
		["bv_gtr_spec_V_gold", 25],
		["bv_gtr_spec_V_green", 25],
		["bv_gtr_spec_V_grey", 25],
		["bv_gtr_spec_V_lavender", 25],
		["bv_gtr_spec_V_light_blue", 25],
		["bv_gtr_spec_V_light_yellow", 25],
		["bv_gtr_spec_V_lime", 25],
		["bv_gtr_spec_V_marina_blue", 25],
		["bv_gtr_spec_V_navy_blue", 25],
		["bv_gtr_spec_V_orange", 25],
		["bv_gtr_spec_V_pink", 25],
		["bv_gtr_spec_V_purple", 25],
		["bv_gtr_spec_V_red", 25],
		["bv_gtr_spec_V_sand", 25],
		["bv_gtr_spec_V_silver", 25],
		["bv_gtr_spec_V_skin_blue", 25],
		["bv_gtr_spec_V_skin_camo", 25],
		["bv_gtr_spec_V_skin_camo_urban", 25],
		["bv_shelly_bf_skin", 25],
		["bv_shelly_bw_skin", 25],
		["bv_shelly_rw_skin", 25],
		["bv_shelly_wb_skin", 25],
		["bv_shelly_wbl_skin", 25],
		["bv_shelly_wf_skin", 25],
		["bv_the_crowner_aqua", 25],
		["bv_the_crowner_baby_blue", 25],
		["bv_the_crowner_baby_pink", 25],
		["bv_the_crowner_black2", 25],
		["bv_the_crowner_burgundy", 25],
		["bv_the_crowner_cardinal", 25],
		["bv_the_crowner_dark_green", 25],
		["bv_the_crowner_gold", 25],
		["bv_the_crowner_green", 25],
		["bv_the_crowner_grey", 25],
		["bv_the_crowner_lavender", 25],
		["bv_the_crowner_light_blue", 25],
		["bv_the_crowner_light_yellow", 25],
		["bv_the_crowner_lime", 25],
		["bv_the_crowner_marina_blue", 25],
		["bv_the_crowner_navy_blue", 25],
		["bv_the_crowner_orange", 25],
		["bv_the_crowner_pink", 25],
		["bv_the_crowner_purple", 25],
		["bv_the_crowner_red", 25],
		["bv_the_crowner_sand", 25],
		["bv_the_crowner_silver", 25],
		["bv_the_crowner_skin_blue", 25],
		["bv_the_crowner_skin_camo", 25],
		["bv_the_crowner_skin_camo_urban", 25],
		["bv_the_crowner_skin_white", 25],

	//class FMPTrucks
		["bv_monster_aqua", 25],
		["bv_monster_baby_blue", 25],
		["bv_monster_baby_pink", 25],
		["bv_monster_black2", 25],
		["bv_monster_burgundy", 25],
		["bv_monster_cardinal", 25],
		["bv_monster_dark_green", 25],
		["bv_monster_gold", 25],
		["bv_monster_green", 25],
		["bv_monster_grey", 25],
		["bv_monster_lavender", 25],
		["bv_monster_light_blue", 25],
		["bv_monster_light_yellow", 25],
		["bv_monster_lime", 25],
		["bv_monster_marina_blue", 25],
		["bv_monster_navy_blue", 25],
		["bv_monster_orange", 25],
		["bv_monster_pink", 25],
		["bv_monster_purple", 25],
		["bv_monster_red", 25],
		["bv_monster_sand", 25],
		["bv_monster_silver", 25],
		["bv_monster_skin_blue", 25],
		["bv_monster_skin_camo", 25],
		["bv_monster_skin_camo_urban", 25],
	//class RHSVehicles
		["RHS_BTR70", 25],
		["RHS_BTR70_MSV", 25],
		["RHS_BTR70_VDV", 25],
		["RHS_BTR70_VMF", 25],
		["RHS_BTR70_VV", 25],
		["RHS_BTR80A_MSV", 25],
		["RHS_BTR80A_VDV", 25],
		["RHS_BTR80A_VMF", 25],
		["RHS_BTR80A_VV", 25],
		["RHS_BTR80_MSV", 25],
		["RHS_BTR80_VDV", 25],
		["RHS_BTR80_VMF", 25],
		["RHS_BTR80_VV", 25],
		["RHS_Civ_Truck_02_covered_F", 25],
		["RHS_Civ_Truck_02_transport_F", 25],
		["RHS_M2A3", 25],
		["RHS_M2A3_BUSKI", 25],
		["RHS_UAZ_MSV_01", 25],
		["RHS_Ural_Civ_01", 25],
		["RHS_Ural_Civ_02", 25],
		["RHS_Ural_Civ_03", 25],
		["RHS_Ural_Flat_MSV_01", 25],
		["RHS_Ural_Flat_VDV_01", 25],
		["RHS_Ural_Flat_VMF_01", 25],
		["RHS_Ural_Flat_VV_01", 25],
		["RHS_Ural_Fuel_MSV_01", 25],
		["RHS_Ural_Fuel_VDV_01", 25],
		["RHS_Ural_Fuel_VMF_01", 25],
		["RHS_Ural_Fuel_VV_01", 25],
		["RHS_Ural_MSV_01", 25],
		["RHS_Ural_Open_Civ_01", 25],
		["RHS_Ural_Open_Civ_02", 25],
		["RHS_Ural_Open_Civ_03", 25],
		["RHS_Ural_Open_Flat_MSV_01", 25],
		["RHS_Ural_Open_Flat_VDV_01", 25],
		["RHS_Ural_Open_Flat_VMF_01", 25],
		["RHS_Ural_Open_Flat_VV_01", 25],
		["RHS_Ural_Open_MSV_01", 25],
		["RHS_Ural_Open_VDV_01", 25],
		["RHS_Ural_Open_VMF_01", 25],
		["RHS_Ural_Open_VV_01", 25],
		["RHS_Ural_Repair_MSV_01", 25],
		["RHS_Ural_Repair_VDV_01", 25],
		["RHS_Ural_Repair_VMF_01", 25],
		["RHS_Ural_Repair_VV_01", 25],
		["RHS_Ural_VDV_01", 25],
		["RHS_Ural_VMF_01", 25],
		["RHS_Ural_VV_01", 25],
		["rhs_bmp3_late_msv", 25],
		["rhs_bmp3mera_msv", 25],
		["rhs_btr60_chdkz", 25],
		["rhs_btr60_vdv", 25],
		["rhs_btr60_vmf", 25],
		["rhs_btr70_chdkz", 25],
		["rhs_gaz66_ammo_msv", 25],
		["rhs_gaz66_ammo_vdv", 25],
		["rhs_gaz66_ammo_vmf", 25],
		["rhs_gaz66_ammo_vv", 25],
		["rhs_gaz66_ap2_msv", 25],
		["rhs_gaz66_ap2_vdv", 25],
		["rhs_gaz66_ap2_vmf", 25],
		["rhs_gaz66_ap2_vv", 25],
		["rhs_gaz66_flat_msv", 25],
		["rhs_gaz66_flat_vdv", 25],
		["rhs_gaz66_flat_vmf", 25],
		["rhs_gaz66_flat_vv", 25],
		["rhs_gaz66_msv", 25],
		["rhs_gaz66_r142_msv", 25],
		["rhs_gaz66_r142_vdv", 25],
		["rhs_gaz66_r142_vmf", 25],
		["rhs_gaz66_r142_vv", 25],
		["rhs_gaz66_repair_msv", 25],
		["rhs_gaz66_repair_vdv", 25],
		["rhs_gaz66_repair_vmf", 25],
		["rhs_gaz66_repair_vv", 25],
		["rhs_gaz66_vdv", 25],
		["rhs_gaz66_vmf", 25],
		["rhs_gaz66_vv", 25],
		["rhs_gaz66o_flat_msv", 25],
		["rhs_gaz66o_flat_vdv", 25],
		["rhs_gaz66o_flat_vmf", 25],
		["rhs_gaz66o_flat_vv", 25],
		["rhs_gaz66o_msv", 25],
		["rhs_gaz66o_vdv", 25],
		["rhs_gaz66o_vmf", 25],
		["rhs_gaz66o_vv", 25],
		["rhs_kamaz5350", 25],
		["rhs_kamaz5350_flatbed", 25],
		["rhs_kamaz5350_flatbed_cover", 25],
		["rhs_kamaz5350_flatbed_cover_msv", 25],
		["rhs_kamaz5350_flatbed_cover_vdv", 25],
		["rhs_kamaz5350_flatbed_cover_vmf", 25],
		["rhs_kamaz5350_flatbed_cover_vv", 25],
		["rhs_kamaz5350_flatbed_msv", 25],
		["rhs_kamaz5350_flatbed_vdv", 25],
		["rhs_kamaz5350_flatbed_vmf", 25],
		["rhs_kamaz5350_flatbed_vv", 25],
		["rhs_kamaz5350_msv", 25],
		["rhs_kamaz5350_open", 25],
		["rhs_kamaz5350_open_msv", 25],
		["rhs_kamaz5350_open_vdv", 25],
		["rhs_kamaz5350_open_vmf", 25],
		["rhs_kamaz5350_open_vv", 25],
		["rhs_kamaz5350_vdv", 25],
		["rhs_kamaz5350_vmf", 25],
		["rhs_kamaz5350_vv", 25],
		["rhs_tigr_3camo_vdv", 25],
		["rhs_tigr_3camo_vmf", 25],
		["rhs_tigr_3camo_vv", 25],
		["rhs_tigr_ffv_3camo_msv", 25],
		["rhs_tigr_ffv_3camo_vdv", 25],
		["rhs_tigr_ffv_3camo_vmf", 25],
		["rhs_tigr_ffv_3camo_vv", 25],
		["rhs_tigr_ffv_msv", 25],
		["rhs_tigr_ffv_vdv", 25],
		["rhs_tigr_ffv_vmf", 25],
		["rhs_tigr_ffv_vv", 25],
		["rhs_tigr_m_3camo_msv", 25],
		["rhs_tigr_m_3camo_vdv", 25],
		["rhs_tigr_m_3camo_vmf", 25],
		["rhs_tigr_m_3camo_vv", 25],
		["rhs_tigr_m_msv", 25],
		["rhs_tigr_m_vdv", 25],
		["rhs_tigr_m_vmf", 25],
		["rhs_tigr_m_vv", 25],
		["rhs_tigr_msv", 25],
		["rhs_tigr_sts_3camo_msv", 25],
		["rhs_tigr_sts_3camo_vdv", 25],
		["rhs_tigr_sts_3camo_vmf", 25],
		["rhs_tigr_sts_3camo_vv", 25],
		["rhs_tigr_sts_msv", 25],
		["rhs_tigr_sts_vdv", 25],
		["rhs_tigr_sts_vmf", 25],
		["rhs_tigr_sts_vv", 25],
		["rhs_tigr_vdv", 25],
		["rhs_tigr_vmf", 25],
		["rhs_tigr_vv", 25],
		["rhs_truck", 25],
		["rhs_typhoon_vdv", 25],
		["rhs_uaz_open_chdkz", 25],
		["rhs_uaz_open_vdv", 25],
		["rhs_uaz_open_vmf", 25],
		["rhs_uaz_open_vv", 25],
		["rhs_uaz_spg9_chdkz", 25],
		["rhs_uaz_vdv", 25],
		["rhs_uaz_vv", 25],
		["rhs_ural_chdkz", 25],
		["rhs_ural_open_chdkz", 25],
		["rhs_ural_work_chdkz", 25],
		["rhs_ural_work_open_chdkz", 25],
		["rhsusf_M1078A1P2_B_CP_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_d_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_d_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_wd_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_d_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_d_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_wd_fmtv_usarmy", 25],
		["rhsusf_M1078A1P2_wd_open_fmtv_usarmy", 25],
		["rhsusf_M1078A1R_SOV_M2_D_fmtv_socom", 25],
		["rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom", 25],
		["rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_D_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_D_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_WD_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_B_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_D_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_D_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_WD_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_WD_open_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_flatbed_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_fmtv_usarmy", 25],
		["rhsusf_M1083A1P2_open_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_D_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_M2_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_WD_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_B_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_D_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_WD_fmtv_usarmy", 25],
		["rhsusf_M1084A1P2_fmtv_usarmy", 25],
		["rhsusf_M1084A1R_SOV_M2_D_fmtv_socom", 25],
		["rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom", 25],
		["rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy", 25],
		["rhsusf_M1085A1P2_B_Medical_fmtv_usarmy", 25],
		["rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy", 25],
		["rhsusf_M1232_M2_usarmy_d", 25],
		["rhsusf_M1232_M2_usarmy_wd", 25],
		["rhsusf_M1232_MK19_usarmy_d", 25],
		["rhsusf_M1232_MK19_usarmy_wd", 25],
		["rhsusf_M1232_usarmy_d", 25],
		["rhsusf_M1232_usarmy_wd", 25],
		["rhsusf_M1237_M2_usarmy_d", 25],
		["rhsusf_M1237_M2_usarmy_wd", 25],
		["rhsusf_M1237_MK19_usarmy_d", 25],
		["rhsusf_M1237_MK19_usarmy_wd", 25],
		["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d", 25],
		["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd", 25],
		["rhsusf_M977A4_AMMO_BKIT_usarmy_d", 25],
		["rhsusf_M977A4_AMMO_BKIT_usarmy_wd", 25],
		["rhsusf_M977A4_AMMO_usarmy_d", 25],
		["rhsusf_M977A4_AMMO_usarmy_wd", 25],
		["rhsusf_M977A4_BKIT_M2_usarmy_d", 25],
		["rhsusf_M977A4_BKIT_M2_usarmy_wd", 25],
		["rhsusf_M977A4_BKIT_usarmy_d", 25],
		["rhsusf_M977A4_BKIT_usarmy_wd", 25],
		["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d", 25],
		["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd", 25],
		["rhsusf_M977A4_REPAIR_BKIT_usarmy_d", 25],
		["rhsusf_M977A4_REPAIR_BKIT_usarmy_wd", 25],
		["rhsusf_M977A4_REPAIR_usarmy_d", 25],
		["rhsusf_M977A4_REPAIR_usarmy_wd", 25],
		["rhsusf_M977A4_usarmy_d", 25],
		["rhsusf_M977A4_usarmy_wd", 25],
		["rhsusf_M978A4_BKIT_usarmy_d", 25],
		["rhsusf_M978A4_BKIT_usarmy_wd", 25],
		["rhsusf_M978A4_usarmy_d", 25],
		["rhsusf_M978A4_usarmy_wd", 25],
		["rhsusf_m1025_d", 25],
		["rhsusf_m1025_d_Mk19", 25],
		["rhsusf_m1025_d_m2", 25],
		["rhsusf_m1025_d_s", 25],
		["rhsusf_m1025_d_s_Mk19", 25],
		["rhsusf_m1025_d_s_m2", 25],
		["rhsusf_m1025_w", 25],
		["rhsusf_m1025_w_m2", 25],
		["rhsusf_m1025_w_mk19", 25],
		["rhsusf_m1025_w_s", 25],
		["rhsusf_m1025_w_s_Mk19", 25],
		["rhsusf_m1025_w_s_m2", 25],
		["rhsusf_m113_usarmy_M240", 25],
		["rhsusf_m113_usarmy_MK19", 25],
		["rhsusf_m113_usarmy_supply", 25],
		["rhsusf_m113_usarmy_unarmed", 25],
		["rhsusf_m113d_usarmy", 25],
		["rhsusf_m113d_usarmy_M240", 25],
		["rhsusf_m113d_usarmy_MK19", 25],
		["rhsusf_m113d_usarmy_medical", 25],
		["rhsusf_m113d_usarmy_supply", 25],
		["rhsusf_m113d_usarmy_unarmed", 25],
		["rhsusf_m1a1aim_tuski_d", 25],
		["rhsusf_m1a1aim_tuski_wd", 25],
		["rhsusf_m1a1aimd_usarmy", 25],
		["rhsusf_m1a1fep_d", 25],
		["rhsusf_m1a1fep_od", 25],
		["rhsusf_m1a1fep_wd", 25],
		["rhsusf_m1a1hc_wd", 25],
		["rhsusf_m1a2sep1d_usarmy", 25],
		["rhsusf_m1a2sep1tuskid_usarmy", 25],
		["rhsusf_m1a2sep1tuskiid_usarmy", 25],
		["rhsusf_m1a2sep1tuskiiwd_usarmy", 25],
		["rhsusf_m1a2sep1tuskiwd_usarmy", 25],
		["rhsusf_m1a2sep1wd_usarmy", 25],
		["rhsusf_m998_d_2dr", 25],
		["rhsusf_m998_d_2dr_fulltop", 25],
		["rhsusf_m998_d_2dr_halftop", 25],
		["rhsusf_m998_d_4dr", 25],
		["rhsusf_m998_d_4dr_fulltop", 25],
		["rhsusf_m998_d_4dr_halftop", 25],
		["rhsusf_m998_d_s_2dr", 25],
		["rhsusf_m998_d_s_2dr_fulltop", 25],
		["rhsusf_m998_d_s_2dr_halftop", 25],
		["rhsusf_m998_d_s_4dr", 25],
		["rhsusf_m998_d_s_4dr_fulltop", 25],
		["rhsusf_m998_d_s_4dr_halftop", 25],
		["rhsusf_m998_w_2dr", 25],
		["rhsusf_m998_w_2dr_fulltop", 25],
		["rhsusf_m998_w_2dr_halftop", 25],
		["rhsusf_m998_w_4dr", 25],
		["rhsusf_m998_w_4dr_fulltop", 25],
		["rhsusf_m998_w_4dr_halftop", 25],
		["rhsusf_m998_w_s_2dr", 25],
		["rhsusf_m998_w_s_2dr_fulltop", 25],
		["rhsusf_m998_w_s_2dr_halftop", 25],
		["rhsusf_m998_w_s_4dr", 25],
		["rhsusf_m998_w_s_4dr_fulltop", 25],
		["rhsusf_mrzr4_d", 25],
		["rhsusf_mrzr4_d_mud", 25],
		["rhsusf_mrzr4_w_mud", 25],
		["rhsusf_rg33_d", 25],
		["rhsusf_rg33_m2_usmc_wd", 25],
		["rhsusf_rg33_m2_wd", 25],
		["rhsusf_rg33_usmc_d", 25],
		["rhsusf_rg33_usmc_wd", 25],
		["rhs_sprut_vdv", 25],
		["rhs_2s3_tv", 25],
		["rhs_bmd1_chdkz", 25],
		["rhs_bmd2_chdkz", 25],
		["rhs_bmd4_vdv", 25],
		["rhs_bmd4ma_vdv", 25],
		["rhs_bmd4m_vdv", 25],
		["rhs_bmp1_chdkz", 25],
		["rhs_bmp1d_chdkz", 25],
		["rhs_bmp1k_chdkz", 25],
		["rhs_bmp1p_chdkz", 25],
		["rhs_bmp2e_chdkz", 25],
		["rhs_bmp2_chdkz", 25],
		["rhs_bmp2d_chdkz", 25],
		["rhs_bmp2k_chdkz", 25],
		["rhsusf_m109_usarmy", 25],
		["rhsusf_m109d_usarmy", 25],
		["rhsusf_M1117_W", 25],
		["rhsusf_m113_usarmy", 25],
		["rhsusf_m113_usarmy_M2_90", 25],
		["rhsusf_m113_usarmy_medical", 25],
		["rhsusf_m113_usarmy_MK19_90", 25],
		["rhs_t72bb_chdkz", 25],
		["rhs_t72bb_tv", 25],
		["rhs_t72bd_tv", 25],
		["rhs_t80", 25],
		["rhs_t80a", 25],
		["rhs_t80b", 25],
		["rhs_t80bk", 25],
		["rhs_t80bv", 25],
		["rhs_t80bvk", 25],
		["rhs_t80u45m", 25],
		["rhs_t80u", 25],
		["rhs_t80ue1", 25],
		["rhs_t80uk", 25],
		["rhs_t80um", 25],
		["rhs_t90_tv", 25],
		["rhs_t90a_tv", 25],
		["rhs_zsu234_chdkz", 25],
	//class RHSChoppers
		["RHS_AH1Z", 25],
		["RHS_AH1Z_CS", 25],
		["RHS_AH1Z_GS", 25],
		["RHS_AH1Z_wd", 25],
		["RHS_AH1Z_wd_CS", 25],
		["RHS_AH1Z_wd_GS", 25],
		["RHS_AH64D", 25],
		["RHS_AH64DGrey", 25],
		["RHS_AH64D_AA", 25],
		["RHS_AH64D_CS", 25],
		["RHS_AH64D_GS", 25],
		["RHS_AH64D_wd", 25],
		["RHS_AH64D_wd_AA", 25],
		["RHS_AH64D_wd_CS", 25],
		["RHS_AH64D_wd_GS", 25],
		["RHS_CH_47F", 25],
		["RHS_CH_47F_10", 25],
		["RHS_CH_47F_light", 25],
		["RHS_Ka52_UPK23_vvs", 25],
		["RHS_Ka52_UPK23_vvsc", 25],
		["RHS_Ka52_vvs", 25],
		["RHS_Ka52_vvsc", 25],
		["RHS_MELB_AH6M", 25],
		["RHS_MELB_AH6M_H", 25],
		["RHS_MELB_AH6M_M", 25],
		["RHS_MELB_H6M", 25],
		["RHS_MELB_MH6M", 25],
		["RHS_MI8MTV3_UPK23_vvs", 25],
		["RHS_MI8MTV3_UPK23_vvsc", 25],
		["RHS_MI8MTV3_vvs", 25],
		["RHS_MI8MTV3_vvsc", 25],
		["RHS_Mi8MTV3_heavy_vdv", 25],
		["RHS_Mi8MTV3_heavy_vvs", 25],
		["RHS_Mi8MTV3_heavy_vvsc", 25],
		["RHS_Mi8mtv3_Cargo_vdv", 25],
		["RHS_Mi8mtv3_Cargo_vvs", 25],
		["RHS_Mi8mtv3_Cargo_vvsc", 25],
		["RHS_Mi24P_AT_vdv", 25],
		["RHS_Mi24P_AT_vvs", 25],
		["RHS_Mi24P_AT_vvsc", 25],
		["RHS_Mi24P_CAS_vdv", 25],
		["RHS_Mi24P_CAS_vvs", 25],
		["RHS_Mi24P_CAS_vvsc", 25],
		["RHS_Mi24P_vdv", 25],
		["RHS_Mi24P_vvs", 25],
		["RHS_Mi24P_vvsc", 25],
		["RHS_Mi24V_AT_vvs", 25],
		["RHS_Mi24V_AT_vvsc", 25],
		["RHS_Mi24V_FAB_vdv", 25],
		["RHS_Mi24V_FAB_vvs", 25],
		["RHS_Mi24V_FAB_vvsc", 25],
		["RHS_Mi24V_UPK23_vdv", 25],
		["RHS_Mi24V_UPK23_vvs", 25],
		["RHS_Mi24V_UPK23_vvsc", 25],
		["RHS_Mi24V_vdv", 25],
		["RHS_Mi24V_vvs", 25],
		["RHS_Mi24V_vvsc", 25],
		["RHS_Mi24Vt_vvs", 25],
		["RHS_Mi24Vt_vvsc", 25],
		["RHS_Mi8AMTSh_FAB_vvs", 25],
		["RHS_Mi8AMTSh_FAB_vvsc", 25],
		["RHS_Mi8AMTSh_UPK23_vvs", 25],
		["RHS_Mi8AMTSh_UPK23_vvsc", 25],
		["RHS_Mi8AMTSh_vvs", 25],
		["RHS_Mi8AMTSh_vvsc", 25],
		["RHS_Mi8AMT_vdv", 25],
		["RHS_Mi8AMT_vvs", 25],
		["RHS_Mi8AMT_vvsc", 25],
		["RHS_Mi8MTV3_FAB_vdv", 25],
		["RHS_Mi8MTV3_FAB_vvs", 25],
		["RHS_Mi8MTV3_FAB_vvsc", 25],
		["RHS_Mi8MTV3_UPK23_vdv", 25],
		["RHS_Mi8MTV3_vdv", 25],
		["RHS_Mi8amt_civilian", 25],
		["RHS_Mi8mt_Cargo_vdv", 25],
		["RHS_Mi8mt_Cargo_vv", 25],
		["RHS_Mi8mt_Cargo_vvsc", 25],
		["RHS_Mi8mt_vdv", 25],
		["RHS_Mi8mt_vv", 25],
		["RHS_Mi8mt_vvs", 25],
		["RHS_Mi8mt_vvsc", 25],
		["RHS_UH1Y", 25],
		["RHS_UH1Y_FFAR", 25],
		["RHS_UH1Y_FFAR_d", 25],
		["RHS_UH1Y_UNARMED_d", 25],
		["RHS_UH1Y_d", 25],
		["RHS_UH60M", 25],
		["RHS_UH60M_MEV", 25],
		["RHS_UH60M_MEV2", 25],
		["RHS_UH60M_MEV_d", 25],
		["RHS_UH60M_d", 25],
		["rhs_Mi8mt_cargo_vvs", 25],
		["rhs_UH1Y_unarmed", 25],
		["rhs_UH60M_MEV2_d", 25],
		["RHS_UH60M2", 25],
		["RHS_UH60M2_d", 25],
		["RHS_UH60M_ESSS", 25],
		["RHS_UH60M_ESSS2", 25],
		["RHS_UH60M_ESSS_d", 25],
		["RHS_UH60M_ESSS2_d", 25],
		["rhs_ka60_c", 25],
		["rhs_ka60_grey", 25],
		["rhs_mi28n_s13_vvs", 25],
		["rhs_mi28n_s13_vvsc", 25],
		["rhs_mi28n_vvs", 25],
		["rhs_mi28n_vvsc", 25],
		["rhsusf_CH53E_USMC", 25],
		["rhsusf_CH53E_USMC_D", 25],

	//class RHSPlanes
		["RHS_A10", 25],
		["RHS_C130J", 25],
		["RHS_Su25SM_CAS_vvs", 25],
		["RHS_Su25SM_CAS_vvsc", 25],
		["RHS_Su25SM_Cluster_vvs", 25],
		["RHS_Su25SM_Cluster_vvsc", 25],
		["RHS_Su25SM_KH29_vvs", 25],
		["RHS_Su25SM_KH29_vvsc", 25],
		["RHS_Su25SM_vvs", 25],
		["RHS_Su25SM_vvsc", 25],
		["RHS_T50_vvs_051", 25],
		["RHS_T50_vvs_052", 25],
		["RHS_T50_vvs_053", 25],
		["RHS_T50_vvs_054", 25],
		["RHS_T50_vvs_blueonblue", 25],
		["RHS_T50_vvs_generic", 25],
		["RHS_T50_vvs_generic_ext", 25],
		["RHS_TU95MS_vvs_chelyabinsk", 25],
		["RHS_TU95MS_vvs_dubna", 25],
		["RHS_TU95MS_vvs_irkutsk", 25],
		["RHS_TU95MS_vvs_old", 25],
		["RHS_TU95MS_vvs_tambov", 25],
		["rhs_mig29sm_vvs", 25],
		["rhs_mig29sm_vvsc", 25],
		["rhs_mig29sm_vmf", 25],
		["rhs_mig29s_vmf", 25],
		["rhs_mig29s_vvs", 25],
		["rhs_mig29s_vvsc", 25],
		["rhs_pchela1t_vvs", 25],
		["rhs_pchela1t_vvsc", 25],
		["rhsusf_f22", 25],
	//class CUPUnarmed
		["CUP_B_HMMWV_Transport_USA", 25],
		["CUP_B_HMMWV_Unarmed_USA", 25],
		["CUP_B_HMMWV_Unarmed_USMC", 25],
		["CUP_B_LR_Transport_CZ_W", 25],
		["CUP_B_LR_Transport_GB_W", 25],
		["CUP_C_UAZ_Open_TK_CIV", 25],
		["CUP_I_BTR40_TKG", 25],
		["CUP_O_UAZ_Open_RU", 25],
		["CUP_O_UAZ_Unarmed_RU", 25],
		["CUP_O_Ural_Empty_RU", 25],
		["CUP_O_Ural_Open_RU", 25],
		["CUP_O_Ural_RU", 25],
		["CUP_O_Ural_Refuel_RU", 25],
		["CUP_O_Ural_Repair_RU", 25],

	//class CUPArmed
		["CUP_BAF_Jackal2_GMG_W", 25],
		["CUP_BAF_Jackal2_L2A1_W", 25],
		["CUP_B_BAF_Coyote_L2A1_W", 25],
		["CUP_B_Dingo_GER_Wdl", 25],
		["CUP_B_FV432_Bulldog_GB_W_RWS", 25],
		["CUP_B_HMMWV_AGS_GPK_ACR", 25],
		["CUP_B_HMMWV_Crows_M2_USA", 25],
		["CUP_B_HMMWV_Crows_MK19_USA", 25],
		["CUP_B_HMMWV_DSHKM_GPK_ACR", 25],
		["CUP_B_HMMWV_M1114_USMC", 25],
		["CUP_B_HMMWV_M2_GPK_USA", 25],
		["CUP_B_HMMWV_M2_USA", 25],
		["CUP_B_HMMWV_M2_USMC", 25],
		["CUP_B_HMMWV_MK19_USMC", 25],
		["CUP_B_HMMWV_SOV_USA", 25],
		["CUP_B_LAV25M240_USMC", 25],
		["CUP_B_LAV25_HQ_USMC", 25],
		["CUP_B_LAV25_USMC", 25],
		["CUP_B_LR_MG_CZ_W", 25],
		["CUP_B_LR_MG_GB_W", 25],
		["CUP_B_LR_Special_CZ_W", 25],
		["CUP_B_Mastiff_HMG_GB_W", 25],
		["CUP_B_Ridgback_HMG_GB_W", 25],
		["CUP_I_Datsun_PK_Random", 25],
		["CUP_I_SUV_Armored_ION", 25],
		["CUP_I_UAZ_MG_UN", 25],
		["CUP_O_BRDM2_CHDKZ", 25],
		["CUP_O_BRDM2_HQ_CHDKZ", 25],
		["CUP_O_BRDM2_HQ_SLA", 25],
		["CUP_O_BRDM2_SLA", 25],
		["CUP_O_BTR90_HQ_RU", 25],
		["CUP_O_BTR90_RU", 25],
		["CUP_O_Datsun_PK_Random", 25],
		["CUP_O_GAZ_Vodnik_PK_RU", 25],
		["CUP_O_LR_MG_TKA", 25],
		["CUP_O_LR_MG_TKM", 25],
		["CUP_O_UAZ_AGS30_RU", 25],
		["CUP_O_UAZ_MG_RU", 25],

	//class CUPChoppers
		["CUP_B_AH1Z_NoWeapons", 25],
		["CUP_B_AH6J_ESCORT_USA", 25],
		["CUP_B_AW159_Unarmed_BAF", 25],
		["CUP_B_CH47F_GB", 25],
		["CUP_B_CH47F_USA", 25],
		["CUP_B_CH53E_GER", 25],
		["CUP_B_CH53E_USMC", 25],
		["CUP_B_CH53E_VIV_GER", 25],
		["CUP_B_MH60S_FFV_USMC", 25],
		["CUP_B_MH60S_USMC", 25],
		["CUP_B_MH6J_USA", 25],
		["CUP_B_MI6A_CDF", 25],
		["CUP_B_Mi171Sh_Unarmed_ACR", 25],
		["CUP_B_Mi17_CDF", 25],
		["CUP_B_Mi17_medevac_CDF", 25],
		["CUP_B_UH1Y_MEV_F", 25],
		["CUP_B_UH1Y_UNA_F", 25],
		["CUP_B_UH60L_FFV_US", 25],
		["CUP_B_UH60L_US", 25],
		["CUP_B_UH60L_Unarmed_FFV_MEV_US", 25],
		["CUP_B_UH60L_Unarmed_FFV_US", 25],
		["CUP_B_UH60L_Unarmed_US", 25],
		["CUP_B_UH60M_FFV_US", 25],
		["CUP_B_UH60M_US", 25],
		["CUP_B_UH60M_Unarmed_FFV_MEV_US", 25],
		["CUP_B_UH60M_Unarmed_FFV_US", 25],
		["CUP_B_UH60M_Unarmed_US", 25],
		["CUP_C_Mi17_Civilian_RU", 25],
		["CUP_I_UH60L_FFV_RACS", 25],
		["CUP_I_UH60L_RACS", 25],
		["CUP_I_UH60L_Unarmed_FFV_MEV_Racs", 25],
		["CUP_I_UH60L_Unarmed_FFV_Racs", 25],
		["CUP_I_UH60L_Unarmed_RACS", 25],
		["CUP_O_Mi17_TK", 25],
		["CUP_O_Mi8_medevac_CHDKZ", 25],
		["CUP_O_Mi8_medevac_RU", 25],

	//class CUPPlanes

		["CUP_B_GR9_CAP_GB", 25],
		["CUP_C_C47_CIV", 25],
		["CUP_O_AN2_TK", 25],
		["CUP_B_A10_AT_USA", 25],
		["CUP_B_A10_CAS_USA", 25],
		["CUP_B_AV8B_CAP_USMC", 25],
		["CUP_B_C130J_Cargo_GB", 25],
		["CUP_B_C130J_Cargo_USMC", 25],
		["CUP_B_C130J_GB", 25],
		["CUP_B_C130J_USMC", 25],
		["CUP_B_MV22_USMC", 25],
		["CUP_C_DC3_CIV", 25],
		["CUP_I_C130J_AAF", 25],
		["CUP_I_C130J_Cargo_AAF", 25],
		["CUP_I_C130J_Cargo_RACS", 25],
		["CUP_I_C130J_RACS", 25],
		["CUP_O_C130J_Cargo_TKA", 25],
		["CUP_O_C130J_TKA", 25],
	//class RHSBoats
		["rhsusf_mkvsoc", 25],
	//class CUPBoats

		["CUP_C_Fishing_Boat_Chernarus", 25],
		["CUP_B_RHIB2Turret_USMC", 25],
		["CUP_B_Seafox_USMC", 25],
		["CUP_B_Seafox_USV_USMC", 25],
		["CUP_B_Zodiac_USMC", 25],


        //new CONTACT
		//Offroad
		["I_E_Offroad_01_F", 25],
		["I_E_Offroad_01_covered_F", 25],
		["I_E_Offroad_01_comms_F", 25],
		["B_GEN_Offroad_01_covered_F", 25],
		["B_GEN_Offroad_01_comms_F", 25],
		["C_Offroad_01_covered_F", 25],
		["C_Offroad_01_comms_F", 25],
		//Trekker
		["C_Tractor_01_F", 25],
		//Zamak
		["I_E_Truck_02_transport_F", 50],
		["I_E_Truck_02_fuel_F", 25],
		["I_E_Truck_02_Ammo_F", 25],
		["I_E_Truck_02_Box_F", 50],
		["I_E_Truck_02_Medical_F", 25],
		//"I_E_Truck_02_MRL_F", 25],
		//Van
		["I_E_Van_02_vehicle_F", 50],
		["I_E_Van_02_transport_MP_F", 50],
		["I_E_Van_02_medevac_F", 50],
		["I_E_APC_tracked_03_cannon_F", 25],
		["I_E_Heli_light_03_unarmed_F", 25],
		//Eagel
		["BWA3_Eagle_Fleck", 25],	
		["BWA3_Eagle_FLW100_Fleck", 25],
		["BWA3_Eagle_Tropen", 25],
		["BWA3_Eagle_FLW100_Tropen", 25],	
		["BWA3_Puma_Fleck", 25],	
		["BWA3_Leopard2_Fleck", 25],
		// Tracked vehicles (Tropen)	
		["BWA3_Puma_Tropen", 25],
		["BWA3_Leopard2_Tropen", 25],
		["BW_Offroad_Feldjager_F", 25],
		["BW_Offroad_F", 25],
		["BW_Offroad_Repair_F", 25],
		["BW_SPw_Fennek_Stan_F", 25],
		["BW_SPw_Fennek_SMG_F", 25],
		["BW_SPw_Fennek_Med_F", 25],
		["BW_MATV_Stan_F", 25],
		["BW_MATV_Med_F", 25],
		["BW_LKW7T_Trans_F", 25],
		["BW_LKW7T_Trans_Cov_F", 50],
		["BW_LKW7T_Med_F", 50],
		["BW_LKW7T_Fuel_F", 25],
		["BW_LKW7T_Ammo_F", 25],
		["BW_LKW7T_Repair_F", 50],
		["BW_LKW7T_Device_F", 50],
		["BW_LKW15T_Multi_F", 50],
		["BW_LKW15T_Fuel_F", 25],
		["BW_LKW15T_Ammo_F", 25],
		["BW_LKW15T_Repair_F", 50],
		["BW_Arma_FLW_F", 25],
        //Boats
		["Exile_Boat_RubberDuck_CSAT", 25],
		["Exile_Boat_RubberDuck_Digital", 25],
		["Exile_Boat_RubberDuck_Orange", 25],
		["Exile_Boat_RubberDuck_Blue", 25],
		["Exile_Boat_RubberDuck_Black", 25],
		["Exile_Boat_MotorBoat_Police", 25],
		["Exile_Boat_MotorBoat_Orange", 25],
		["Exile_Boat_MotorBoat_White", 25],
		["Exile_Boat_SDV_CSAT", 50],
		["Exile_Boat_SDV_Digital", 50],
		["Exile_Boat_SDV_Grey", 50],
		["I_Boat_Armed_01_minigun_F", 25],
		//USS Freedom
		//"Land_Carrier_01_base_F",
		//Apex Boat
		["B_T_Boat_Transport_01_F", 50],
		["B_T_Lifeboat", 50],
		["O_T_Lifeboat", 50],
		["B_T_Boat_Armed_01_minigun_F", 25],
		["O_T_Boat_Armed_01_hmg_F", 25],
		["O_T_Boat_Transport_01_F", 25],
		["I_C_Boat_Transport_01_F", 25],
		["B_G_Boat_Transport_02_F", 25],
		["O_G_Boat_Transport_02_F", 25],
		["I_G_Boat_Transport_02_F", 25],
		["I_C_Boat_Transport_02_F", 25],
		["C_Boat_Transport_02_F", 25],
		//["C_Scooter_Transport_01_F", 25],
		//"Burnes_LCAC_1", 75],
		//"Burnes_MK10_1", 75],
		["sab_boat", 50],
		["sab_boat_2", 50],
		["sab_boat_3", 50],
		["sab_boat_4", 50]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[

];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[

];